/*
 * ejs.db.slots.h -- Property slot definitions for the "ejs.db" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 0.9.8.
 */

#ifndef _h_SLOTS_EjsDbSlots
#define _h_SLOTS_EjsDbSlots 1


/**
 * Slots for the "ejs.db" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "Database" class 
 */
#define ES_ejs_db_Database__origin                                     5
#define ES_ejs_db_Database_Database                                    5
#define ES_ejs_db_Database__initializer__Database_initializer          6
#define ES_ejs_db_Database__defaultDb                                  7
#define ES_ejs_db_Database__traceSql                                   8
#define ES_ejs_db_Database_connect                                     9
#define ES_ejs_db_Database_close                                       10
#define ES_ejs_db_Database_sql                                         11
#define ES_ejs_db_Database_query                                       12
#define ES_ejs_db_Database_connection                                  13
#define ES_ejs_db_Database_name                                        14
#define ES_ejs_db_Database_getTables                                   15
#define ES_ejs_db_Database_getColumns                                  16
#define ES_ejs_db_Database_defaultDatabase                             17
#define ES_ejs_db_Database_set_defaultDatabase                         18
#define ES_ejs_db_Database_DatatypeToSqlite                            19
#define ES_ejs_db_Database_SqliteToDatatype                            20
#define ES_ejs_db_Database_SqliteToEjs                                 21
#define ES_ejs_db_Database_createDatabase                              22
#define ES_ejs_db_Database_destroyDatabase                             23
#define ES_ejs_db_Database_createTable                                 24
#define ES_ejs_db_Database_renameTable                                 25
#define ES_ejs_db_Database_destroyTable                                26
#define ES_ejs_db_Database_addIndex                                    27
#define ES_ejs_db_Database_removeIndex                                 28
#define ES_ejs_db_Database_addColumn                                   29
#define ES_ejs_db_Database_changeColumn                                30
#define ES_ejs_db_Database_renameColumn                                31
#define ES_ejs_db_Database_removeColumns                               32
#define ES_ejs_db_Database_log                                         33
#define ES_ejs_db_Database_trace                                       34
#define ES_ejs_db_Database_NUM_CLASS_PROP                              35

/**
 * Instance slots for "Database" type 
 */
#define ES_ejs_db_Database__name                                       0
#define ES_ejs_db_Database__connection                                 1
#define ES_ejs_db_Database_NUM_INSTANCE_PROP                           2

/**
 * 
 *    Local slots for methods in type Database 
 */
#define ES_ejs_db_Database_Database_connectionString                   0
#define ES_ejs_db_Database_connect_connectionString                    0
#define ES_ejs_db_Database_sql_cmd                                     0
#define ES_ejs_db_Database_query_cmd                                   0
#define ES_ejs_db_Database_getTables_cmd                               0
#define ES_ejs_db_Database_getTables_grid                              1
#define ES_ejs_db_Database_getTables_result                            2
#define ES_ejs_db_Database_getTables__hoisted_3_row                    3
#define ES_ejs_db_Database_getTables__hoisted_4_name                   4
#define ES_ejs_db_Database_getColumns_table                            0
#define ES_ejs_db_Database_getColumns_names                            1
#define ES_ejs_db_Database_getColumns__hoisted_2_row                   2
#define ES_ejs_db_Database_getColumns__hoisted_3_name                  3
#define ES_ejs_db_Database_set_defaultDatabase_db                      0
#define ES_ejs_db_Database_createDatabase_name                         0
#define ES_ejs_db_Database_createDatabase_options                      1
#define ES_ejs_db_Database_destroyDatabase_name                        0
#define ES_ejs_db_Database_createTable_table                           0
#define ES_ejs_db_Database_createTable_columns                         1
#define ES_ejs_db_Database_createTable_cmd                             2
#define ES_ejs_db_Database_createTable__hoisted_3_colspec              3
#define ES_ejs_db_Database_createTable__hoisted_4_spec                 4
#define ES_ejs_db_Database_createTable__hoisted_5_column               5
#define ES_ejs_db_Database_createTable__hoisted_6_datatype             6
#define ES_ejs_db_Database_renameTable_oldTable                        0
#define ES_ejs_db_Database_renameTable_newTable                        1
#define ES_ejs_db_Database_destroyTable_table                          0
#define ES_ejs_db_Database_addIndex_table                              0
#define ES_ejs_db_Database_addIndex_column                             1
#define ES_ejs_db_Database_addIndex_indexName                          2
#define ES_ejs_db_Database_removeIndex_table                           0
#define ES_ejs_db_Database_removeIndex_indexName                       1
#define ES_ejs_db_Database_addColumn_table                             0
#define ES_ejs_db_Database_addColumn_column                            1
#define ES_ejs_db_Database_addColumn_datatype                          2
#define ES_ejs_db_Database_addColumn_options                           3
#define ES_ejs_db_Database_changeColumn_table                          0
#define ES_ejs_db_Database_changeColumn_column                         1
#define ES_ejs_db_Database_changeColumn_datatype                       2
#define ES_ejs_db_Database_changeColumn_options                        3
#define ES_ejs_db_Database_renameColumn_table                          0
#define ES_ejs_db_Database_renameColumn_oldColumn                      1
#define ES_ejs_db_Database_renameColumn_newColumn                      2
#define ES_ejs_db_Database_removeColumns_table                         0
#define ES_ejs_db_Database_removeColumns_columns                       1
#define ES_ejs_db_Database_removeColumns__hoisted_2_column             2
#define ES_ejs_db_Database_removeColumns__hoisted_4_row                4
#define ES_ejs_db_Database_removeColumns__hoisted_5_name               5
#define ES_ejs_db_Database_removeColumns__hoisted_7_k                  7
#define ES_ejs_db_Database_log_cmd                                     0
#define ES_ejs_db_Database_trace_on                                    0


/**
 *   Class property slots for the "Record" class 
 */
#define ES_ejs_db_Record__origin                                       5
#define ES_ejs_db_Record__initializer__Record_initializer              5
#define ES_ejs_db_Record__belongsTo                                    6
#define ES_ejs_db_Record__className                                    7
#define ES_ejs_db_Record__columnNames                                  8
#define ES_ejs_db_Record__columnTypes                                  9
#define ES_ejs_db_Record__sqlColumnTypes                               10
#define ES_ejs_db_Record__db                                           11
#define ES_ejs_db_Record__foreignId                                    12
#define ES_ejs_db_Record__keyName                                      13
#define ES_ejs_db_Record__tableName                                    14
#define ES_ejs_db_Record__traceSql                                     15
#define ES_ejs_db_Record__validations                                  16
#define ES_ejs_db_Record__beforeFilters                                17
#define ES_ejs_db_Record__afterFilters                                 18
#define ES_ejs_db_Record__wrapFilters                                  19
#define ES_ejs_db_Record_constructor                                   20
#define ES_ejs_db_Record_beforeFilter                                  21
#define ES_ejs_db_Record_afterFilter                                   22
#define ES_ejs_db_Record_wrapFilter                                    23
#define ES_ejs_db_Record_runFilters                                    24
#define ES_ejs_db_Record_save                                          25
#define ES_ejs_db_Record_saveUpdate                                    26
#define ES_ejs_db_Record_belongsTo                                     27
#define ES_ejs_db_Record_createRecord                                  28
#define ES_ejs_db_Record_find                                          29
#define ES_ejs_db_Record_findAll                                       30
#define ES_ejs_db_Record_findOneWhere                                  31
#define ES_ejs_db_Record_findWhere                                     32
#define ES_ejs_db_Record_includeJoin                                   33
#define ES_ejs_db_Record_innerFind                                     34
#define ES_ejs_db_Record_getDb                                         35
#define ES_ejs_db_Record_columnNames                                   36
#define ES_ejs_db_Record_columnTitles                                  37
#define ES_ejs_db_Record_getKeyName                                    38
#define ES_ejs_db_Record_getNumRows                                    39
#define ES_ejs_db_Record_getSchema                                     40
#define ES_ejs_db_Record_getTableName                                  41
#define ES_ejs_db_Record_hasMany                                       42
#define ES_ejs_db_Record_hasAndBelongsToMany                           43
#define ES_ejs_db_Record_hasOne                                        44
#define ES_ejs_db_Record_loadReference                                 45
#define ES_ejs_db_Record_log                                           46
#define ES_ejs_db_Record_logResult                                     47
#define ES_ejs_db_Record_mapSqlTypeToEjs                               48
#define ES_ejs_db_Record_remove                                        49
#define ES_ejs_db_Record_setDb                                         50
#define ES_ejs_db_Record_setup                                         51
#define ES_ejs_db_Record_setTableName                                  52
#define ES_ejs_db_Record_setKeyName                                    53
#define ES_ejs_db_Record_sql                                           54
#define ES_ejs_db_Record_trace                                         55
#define ES_ejs_db_Record_validateFormat                                56
#define ES_ejs_db_Record_validateNumber                                57
#define ES_ejs_db_Record_validatePresence                              58
#define ES_ejs_db_Record_validateUnique                                59
#define ES_ejs_db_Record_ErrorMessages                                 60
#define ES_ejs_db_Record_checkFormat                                   61
#define ES_ejs_db_Record_checkNumber                                   62
#define ES_ejs_db_Record_checkPresent                                  63
#define ES_ejs_db_Record_checkUnique                                   64
#define ES_ejs_db_Record_error                                         65
#define ES_ejs_db_Record_validateModel                                 66
#define ES_ejs_db_Record_getErrors                                     67
#define ES_ejs_db_Record_hasError                                      68
#define ES_ejs_db_Record_getFieldType                                  69
#define ES_ejs_db_Record_coerceTypes                                   70
#define ES_ejs_db_Record_NUM_CLASS_PROP                                71

/**
 * Instance slots for "Record" type 
 */
#define ES_ejs_db_Record__keyValue                                     0
#define ES_ejs_db_Record__errors                                       1
#define ES_ejs_db_Record_NUM_INSTANCE_PROP                             2

/**
 * 
 *    Local slots for methods in type Record 
 */
#define ES_ejs_db_Record_constructor_fields                            0
#define ES_ejs_db_Record_constructor__hoisted_1_field                  1
#define ES_ejs_db_Record_beforeFilter_fn                               0
#define ES_ejs_db_Record_beforeFilter_options                          1
#define ES_ejs_db_Record_afterFilter_fn                                0
#define ES_ejs_db_Record_afterFilter_options                           1
#define ES_ejs_db_Record_wrapFilter_fn                                 0
#define ES_ejs_db_Record_wrapFilter_options                            1
#define ES_ejs_db_Record_runFilters_filters                            0
#define ES_ejs_db_Record_runFilters__hoisted_1_filter                  1
#define ES_ejs_db_Record_runFilters__hoisted_2_fn                      2
#define ES_ejs_db_Record_runFilters__hoisted_3_options                 3
#define ES_ejs_db_Record_save_sql                                      0
#define ES_ejs_db_Record_save_result                                   1
#define ES_ejs_db_Record_save__hoisted_2_field                         2
#define ES_ejs_db_Record_save__hoisted_3_field                         3
#define ES_ejs_db_Record_save__hoisted_5_field                         5
#define ES_ejs_db_Record_saveUpdate_fields                             0
#define ES_ejs_db_Record_saveUpdate__hoisted_1_field                   1
#define ES_ejs_db_Record_belongsTo_owner                               0
#define ES_ejs_db_Record_belongsTo_options                             1
#define ES_ejs_db_Record_createRecord_rowData                          0
#define ES_ejs_db_Record_createRecord_rec                              1
#define ES_ejs_db_Record_createRecord__hoisted_2_field                 2
#define ES_ejs_db_Record_find_key                                      0
#define ES_ejs_db_Record_find_options                                  1
#define ES_ejs_db_Record_find_grid                                     2
#define ES_ejs_db_Record_findAll_options                               0
#define ES_ejs_db_Record_findAll_grid                                  1
#define ES_ejs_db_Record_findAll__hoisted_2_i                          2
#define ES_ejs_db_Record_findOneWhere_where                            0
#define ES_ejs_db_Record_findOneWhere_grid                             1
#define ES_ejs_db_Record_findWhere_where                               0
#define ES_ejs_db_Record_findWhere_count                               1
#define ES_ejs_db_Record_findWhere_grid                                2
#define ES_ejs_db_Record_findWhere__hoisted_3_i                        3
#define ES_ejs_db_Record_includeJoin_joins                             0
#define ES_ejs_db_Record_includeJoin_cmd                               1
#define ES_ejs_db_Record_includeJoin__hoisted_2_join                   2
#define ES_ejs_db_Record_innerFind_key                                 0
#define ES_ejs_db_Record_innerFind_options                             1
#define ES_ejs_db_Record_innerFind_cmd                                 2
#define ES_ejs_db_Record_innerFind_columns                             3
#define ES_ejs_db_Record_innerFind_from                                4
#define ES_ejs_db_Record_innerFind_conditions                          5
#define ES_ejs_db_Record_innerFind_where                               6
#define ES_ejs_db_Record_innerFind_db                                  7
#define ES_ejs_db_Record_innerFind_results                             8
#define ES_ejs_db_Record_innerFind__hoisted_9_index                    9
#define ES_ejs_db_Record_innerFind__hoisted_11_owner                   11
#define ES_ejs_db_Record_innerFind__hoisted_12_owner                   12
#define ES_ejs_db_Record_innerFind__hoisted_13_tname                   13
#define ES_ejs_db_Record_innerFind__hoisted_14_parts                   14
#define ES_ejs_db_Record_innerFind__hoisted_16_cond                    16
#define ES_ejs_db_Record_innerFind__hoisted_17_field                   17
#define ES_ejs_db_Record_innerFind__hoisted_19_e                       19
#define ES_ejs_db_Record_columnNames_result                            0
#define ES_ejs_db_Record_columnNames__hoisted_1_name                   1
#define ES_ejs_db_Record_columnTitles_result                           0
#define ES_ejs_db_Record_columnTitles__hoisted_1_title                 1
#define ES_ejs_db_Record_getNumRows_cmd                                0
#define ES_ejs_db_Record_getNumRows_grid                               1
#define ES_ejs_db_Record_getSchema_sql                                 0
#define ES_ejs_db_Record_getSchema_grid                                1
#define ES_ejs_db_Record_getSchema__hoisted_2_row                      2
#define ES_ejs_db_Record_getSchema__hoisted_3_name                     3
#define ES_ejs_db_Record_hasMany_model                                 0
#define ES_ejs_db_Record_hasMany_options                               1
#define ES_ejs_db_Record_hasAndBelongsToMany_thing                     0
#define ES_ejs_db_Record_hasAndBelongsToMany_options                   1
#define ES_ejs_db_Record_hasOne_model                                  0
#define ES_ejs_db_Record_hasOne_options                                1
#define ES_ejs_db_Record_loadReference_model                           0
#define ES_ejs_db_Record_loadReference_key                             1
#define ES_ejs_db_Record_loadReference_hasMany                         2
#define ES_ejs_db_Record_loadReference_data                            3
#define ES_ejs_db_Record_loadReference__hoisted_4_result               4
#define ES_ejs_db_Record_loadReference__hoisted_5_item                 5
#define ES_ejs_db_Record_log_where                                     0
#define ES_ejs_db_Record_log_cmd                                       1
#define ES_ejs_db_Record_logResult_data                                0
#define ES_ejs_db_Record_mapSqlTypeToEjs_sqlType                       0
#define ES_ejs_db_Record_mapSqlTypeToEjs_ejsType                       1
#define ES_ejs_db_Record_remove_keys                                   0
#define ES_ejs_db_Record_remove__hoisted_1_key                         1
#define ES_ejs_db_Record_remove__hoisted_2_cmd                         2
#define ES_ejs_db_Record_setDb_dbase                                   0
#define ES_ejs_db_Record_setup_database                                0
#define ES_ejs_db_Record_setTableName_name                             0
#define ES_ejs_db_Record_setKeyName_value                              0
#define ES_ejs_db_Record_sql_cmd                                       0
#define ES_ejs_db_Record_sql_count                                     1
#define ES_ejs_db_Record_trace_on                                      0
#define ES_ejs_db_Record_validateFormat_fields                         0
#define ES_ejs_db_Record_validateFormat_options                        1
#define ES_ejs_db_Record_validateNumber_fields                         0
#define ES_ejs_db_Record_validateNumber_options                        1
#define ES_ejs_db_Record_validatePresence_fields                       0
#define ES_ejs_db_Record_validatePresence_options                      1
#define ES_ejs_db_Record_validateUnique_fields                         0
#define ES_ejs_db_Record_validateUnique_options                        1
#define ES_ejs_db_Record_checkFormat_thisObj                           0
#define ES_ejs_db_Record_checkFormat_field                             1
#define ES_ejs_db_Record_checkFormat_value                             2
#define ES_ejs_db_Record_checkFormat_options                           3
#define ES_ejs_db_Record_checkNumber_thisObj                           0
#define ES_ejs_db_Record_checkNumber_field                             1
#define ES_ejs_db_Record_checkNumber_value                             2
#define ES_ejs_db_Record_checkNumber_options                           3
#define ES_ejs_db_Record_checkPresent_thisObj                          0
#define ES_ejs_db_Record_checkPresent_field                            1
#define ES_ejs_db_Record_checkPresent_value                            2
#define ES_ejs_db_Record_checkPresent_options                          3
#define ES_ejs_db_Record_checkUnique_thisObj                           0
#define ES_ejs_db_Record_checkUnique_field                             1
#define ES_ejs_db_Record_checkUnique_value                             2
#define ES_ejs_db_Record_checkUnique_options                           3
#define ES_ejs_db_Record_error_field                                   0
#define ES_ejs_db_Record_error_msg                                     1
#define ES_ejs_db_Record_validateModel__hoisted_0_validation           0
#define ES_ejs_db_Record_validateModel__hoisted_1_field                1
#define ES_ejs_db_Record_hasError_field                                0
#define ES_ejs_db_Record_getFieldType_field                            0
#define ES_ejs_db_Record_coerceTypes__hoisted_0_field                  0
#define ES_ejs_db_Record_coerceTypes__hoisted_1_value                  1

#define _ES_CHECKSUM_ejs_db 1141514

#endif
