/*
 * ejs.io.slots.h -- Property slot definitions for the "ejs.io" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 0.9.8.
 */

#ifndef _h_SLOTS_EjsIoSlots
#define _h_SLOTS_EjsIoSlots 1


/**
 * Slots for the "ejs.io" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "BinaryStream" class 
 */
#define ES_ejs_io_BinaryStream__origin                                 5
#define ES_ejs_io_BinaryStream_BinaryStream                            5
#define ES_ejs_io_BinaryStream__initializer__BinaryStream_initializer  6
#define ES_ejs_io_BinaryStream_BigEndian                               7
#define ES_ejs_io_BinaryStream_LittleEndian                            8
#define ES_ejs_io_BinaryStream_close                                   9
#define ES_ejs_io_BinaryStream_endian                                  10
#define ES_ejs_io_BinaryStream_set_endian                              11
#define ES_ejs_io_BinaryStream_flush                                   12
#define ES_ejs_io_BinaryStream_read                                    13
#define ES_ejs_io_BinaryStream_readBoolean                             14
#define ES_ejs_io_BinaryStream_readByte                                15
#define ES_ejs_io_BinaryStream_readByteArray                           16
#define ES_ejs_io_BinaryStream_readDate                                17
#define ES_ejs_io_BinaryStream_readDouble                              18
#define ES_ejs_io_BinaryStream_readInteger                             19
#define ES_ejs_io_BinaryStream_readLong                                20
#define ES_ejs_io_BinaryStream_readString                              21
#define ES_ejs_io_BinaryStream_readXML                                 22
#define ES_ejs_io_BinaryStream_write                                   23
#define ES_ejs_io_BinaryStream_writeByte                               24
#define ES_ejs_io_BinaryStream_writeShort                              25
#define ES_ejs_io_BinaryStream_writeDouble                             26
#define ES_ejs_io_BinaryStream_writeInteger                            27
#define ES_ejs_io_BinaryStream_writeLong                               28
#define ES_ejs_io_BinaryStream_NUM_CLASS_PROP                          29

/**
 * Instance slots for "BinaryStream" type 
 */
#define ES_ejs_io_BinaryStream_inbuf                                   0
#define ES_ejs_io_BinaryStream_outbuf                                  1
#define ES_ejs_io_BinaryStream_nextStream                              2
#define ES_ejs_io_BinaryStream_NUM_INSTANCE_PROP                       3

/**
 * 
 *    Local slots for methods in type BinaryStream 
 */
#define ES_ejs_io_BinaryStream_BinaryStream_stream                     0
#define ES_ejs_io_BinaryStream_BinaryStream___fun_6051__               1
#define ES_ejs_io_BinaryStream_BinaryStream___fun_6072__               2
#define ES_ejs_io_BinaryStream_close_graceful                          0
#define ES_ejs_io_BinaryStream_set_endian_value                        0
#define ES_ejs_io_BinaryStream_read_buffer                             0
#define ES_ejs_io_BinaryStream_read_offset                             1
#define ES_ejs_io_BinaryStream_read_count                              2
#define ES_ejs_io_BinaryStream_readByteArray_count                     0
#define ES_ejs_io_BinaryStream_readString_count                        0
#define ES_ejs_io_BinaryStream_readXML_data                            0
#define ES_ejs_io_BinaryStream_readXML_s                               1
#define ES_ejs_io_BinaryStream_write_items                             0
#define ES_ejs_io_BinaryStream_write_count                             1
#define ES_ejs_io_BinaryStream_write__hoisted_2_i                      2
#define ES_ejs_io_BinaryStream_writeByte_data                          0
#define ES_ejs_io_BinaryStream_writeShort_data                         0
#define ES_ejs_io_BinaryStream_writeDouble_data                        0
#define ES_ejs_io_BinaryStream_writeInteger_data                       0
#define ES_ejs_io_BinaryStream_writeLong_data                          0


/**
 *   Class property slots for the "File" class 
 */
#define ES_ejs_io_File__origin                                         5
#define ES_ejs_io_File_File                                            5
#define ES_ejs_io_File__initializer__File_initializer                  6
#define ES_ejs_io_File_Closed                                          7
#define ES_ejs_io_File_Open                                            8
#define ES_ejs_io_File_Read                                            9
#define ES_ejs_io_File_Write                                           10
#define ES_ejs_io_File_Append                                          11
#define ES_ejs_io_File_Create                                          12
#define ES_ejs_io_File_Truncate                                        13
#define ES_ejs_io_File_absolutePath                                    14
#define ES_ejs_io_File_basename                                        15
#define ES_ejs_io_File_close                                           16
#define ES_ejs_io_File_copy                                            17
#define ES_ejs_io_File_createTempFile                                  18
#define ES_ejs_io_File_created                                         19
#define ES_ejs_io_File_dirname                                         20
#define ES_ejs_io_File_exists                                          21
#define ES_ejs_io_File_extension                                       22
#define ES_ejs_io_File_flush                                           23
#define ES_ejs_io_File_freeSpace                                       24
#define ES_ejs_io_File_getFiles                                        25
#define ES_ejs_io_File_getBytes                                        26
#define ES_ejs_io_File_getLines                                        27
#define ES_ejs_io_File_getString                                       28
#define ES_ejs_io_File_getXML                                          29
#define ES_ejs_io_File_hasDriveSpec                                    30
#define ES_ejs_io_File_isDir                                           31
#define ES_ejs_io_File_isOpen                                          32
#define ES_ejs_io_File_isRegular                                       33
#define ES_ejs_io_File_lastAccess                                      34
#define ES_ejs_io_File_makeDir                                         35
#define ES_ejs_io_File_mode                                            36
#define ES_ejs_io_File_modified                                        37
#define ES_ejs_io_File_name                                            38
#define ES_ejs_io_File_newline                                         39
#define ES_ejs_io_File_set_newline                                     40
#define ES_ejs_io_File_open                                            41
#define ES_ejs_io_File_openFileStream                                  42
#define ES_ejs_io_File_openTextStream                                  43
#define ES_ejs_io_File_openBinaryStream                                44
#define ES_ejs_io_File_pathDelimiter                                   45
#define ES_ejs_io_File_set_pathDelimiter                               46
#define ES_ejs_io_File_parent                                          47
#define ES_ejs_io_File_permissions                                     48
#define ES_ejs_io_File_set_permissions                                 49
#define ES_ejs_io_File_position                                        50
#define ES_ejs_io_File_set_position                                    51
#define ES_ejs_io_File_put                                             52
#define ES_ejs_io_File_relativePath                                    53
#define ES_ejs_io_File_read                                            54
#define ES_ejs_io_File_readBytes                                       55
#define ES_ejs_io_File_remove                                          56
#define ES_ejs_io_File_removeDir                                       57
#define ES_ejs_io_File_rename                                          58
#define ES_ejs_io_File_setCallback                                     59
#define ES_ejs_io_File_unixPath                                        60
#define ES_ejs_io_File_write                                           61
#define ES_ejs_io_File_NUM_CLASS_PROP                                  62

/**
 * Instance slots for "File" type 
 */
#define ES_ejs_io_File_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type File 
 */
#define ES_ejs_io_File_File_path                                       0
#define ES_ejs_io_File_close_graceful                                  0
#define ES_ejs_io_File_copy_toPath                                     0
#define ES_ejs_io_File_createTempFile_directory                        0
#define ES_ejs_io_File_freeSpace_path                                  0
#define ES_ejs_io_File_getFiles_enumDirs                               0
#define ES_ejs_io_File_getBytes_path                                   0
#define ES_ejs_io_File_getLines_path                                   0
#define ES_ejs_io_File_getLines_encoding                               1
#define ES_ejs_io_File_getString_path                                  0
#define ES_ejs_io_File_getString_encoding                              1
#define ES_ejs_io_File_getXML_path                                     0
#define ES_ejs_io_File_makeDir_permissions                             0
#define ES_ejs_io_File_set_newline_terminator                          0
#define ES_ejs_io_File_open_mode                                       0
#define ES_ejs_io_File_open_permissions                                1
#define ES_ejs_io_File_openFileStream_filename                         0
#define ES_ejs_io_File_openFileStream_mode                             1
#define ES_ejs_io_File_openFileStream_permissions                      2
#define ES_ejs_io_File_openFileStream_file                             3
#define ES_ejs_io_File_openTextStream_filename                         0
#define ES_ejs_io_File_openTextStream_mode                             1
#define ES_ejs_io_File_openTextStream_permissions                      2
#define ES_ejs_io_File_openTextStream_file                             3
#define ES_ejs_io_File_openBinaryStream_filename                       0
#define ES_ejs_io_File_openBinaryStream_mode                           1
#define ES_ejs_io_File_openBinaryStream_permissions                    2
#define ES_ejs_io_File_openBinaryStream_file                           3
#define ES_ejs_io_File_set_pathDelimiter_delim                         0
#define ES_ejs_io_File_set_permissions_mask                            0
#define ES_ejs_io_File_set_position_value                              0
#define ES_ejs_io_File_put_path                                        0
#define ES_ejs_io_File_put_permissions                                 1
#define ES_ejs_io_File_put_args                                        2
#define ES_ejs_io_File_read_buffer                                     0
#define ES_ejs_io_File_read_offset                                     1
#define ES_ejs_io_File_read_count                                      2
#define ES_ejs_io_File_readBytes_count                                 0
#define ES_ejs_io_File_removeDir_recursive                             0
#define ES_ejs_io_File_rename_toFile                                   0
#define ES_ejs_io_File_setCallback_callback                            0
#define ES_ejs_io_File_write_items                                     0


/**
 *   Class property slots for the "Http" class 
 */
#define ES_ejs_io_Http__origin                                         5
#define ES_ejs_io_Http_Http                                            5
#define ES_ejs_io_Http__initializer__Http_initializer                  6
#define ES_ejs_io_Http_Continue                                        7
#define ES_ejs_io_Http_Ok                                              8
#define ES_ejs_io_Http_Created                                         9
#define ES_ejs_io_Http_Accepted                                        10
#define ES_ejs_io_Http_NotAuthoritative                                11
#define ES_ejs_io_Http_NoContent                                       12
#define ES_ejs_io_Http_Reset                                           13
#define ES_ejs_io_Http_Partial                                         14
#define ES_ejs_io_Http_MultipleChoice                                  15
#define ES_ejs_io_Http_MovedPermanently                                16
#define ES_ejs_io_Http_MovedTemporarily                                17
#define ES_ejs_io_Http_SeeOther                                        18
#define ES_ejs_io_Http_NotModified                                     19
#define ES_ejs_io_Http_UseProxy                                        20
#define ES_ejs_io_Http_BadRequest                                      21
#define ES_ejs_io_Http_Unauthorized                                    22
#define ES_ejs_io_Http_PaymentRequired                                 23
#define ES_ejs_io_Http_Forbidden                                       24
#define ES_ejs_io_Http_NotFound                                        25
#define ES_ejs_io_Http_BadMethod                                       26
#define ES_ejs_io_Http_NotAccepted                                     27
#define ES_ejs_io_Http_ProxyAuth                                       28
#define ES_ejs_io_Http_ClientTimeout                                   29
#define ES_ejs_io_Http_Conflict                                        30
#define ES_ejs_io_Http_Gone                                            31
#define ES_ejs_io_Http_LengthRequired                                  32
#define ES_ejs_io_Http_PrecondFailed                                   33
#define ES_ejs_io_Http_EntityTooLarge                                  34
#define ES_ejs_io_Http_ReqTooLong                                      35
#define ES_ejs_io_Http_UnsupportedType                                 36
#define ES_ejs_io_Http_ServerError                                     37
#define ES_ejs_io_Http_NotImplemented                                  38
#define ES_ejs_io_Http_BadGateway                                      39
#define ES_ejs_io_Http_Unavailable                                     40
#define ES_ejs_io_Http_GatewayTimeout                                  41
#define ES_ejs_io_Http_Version                                         42
#define ES_ejs_io_Http_addRequestHeader                                43
#define ES_ejs_io_Http_available                                       44
#define ES_ejs_io_Http_set_callback                                    45
#define ES_ejs_io_Http_callback                                        46
#define ES_ejs_io_Http_close                                           47
#define ES_ejs_io_Http_connect                                         48
#define ES_ejs_io_Http_certificateFile                                 49
#define ES_ejs_io_Http_set_certificateFile                             50
#define ES_ejs_io_Http_code                                            51
#define ES_ejs_io_Http_codeString                                      52
#define ES_ejs_io_Http_contentEncoding                                 53
#define ES_ejs_io_Http_contentLength                                   54
#define ES_ejs_io_Http_contentType                                     55
#define ES_ejs_io_Http_date                                            56
#define ES_ejs_io_Http_del                                             57
#define ES_ejs_io_Http_expires                                         58
#define ES_ejs_io_Http_flush                                           59
#define ES_ejs_io_Http_followRedirects                                 60
#define ES_ejs_io_Http_set_followRedirects                             61
#define ES_ejs_io_Http_form                                            62
#define ES_ejs_io_Http_get                                             63
#define ES_ejs_io_Http_head                                            64
#define ES_ejs_io_Http_header                                          65
#define ES_ejs_io_Http_headers                                         66
#define ES_ejs_io_Http_isSecure                                        67
#define ES_ejs_io_Http_keyFile                                         68
#define ES_ejs_io_Http_set_keyFile                                     69
#define ES_ejs_io_Http_lastModified                                    70
#define ES_ejs_io_Http_method                                          71
#define ES_ejs_io_Http_set_method                                      72
#define ES_ejs_io_Http_post                                            73
#define ES_ejs_io_Http_set_postLength                                  74
#define ES_ejs_io_Http_postLength                                      75
#define ES_ejs_io_Http_set_postData                                    76
#define ES_ejs_io_Http_put                                             77
#define ES_ejs_io_Http_read                                            78
#define ES_ejs_io_Http_readString                                      79
#define ES_ejs_io_Http_readLines                                       80
#define ES_ejs_io_Http_readXml                                         81
#define ES_ejs_io_Http_requestStream                                   82
#define ES_ejs_io_Http_response                                        83
#define ES_ejs_io_Http_responseStream                                  84
#define ES_ejs_io_Http_setCredentials                                  85
#define ES_ejs_io_Http_timeout                                         86
#define ES_ejs_io_Http_set_timeout                                     87
#define ES_ejs_io_Http_upload                                          88
#define ES_ejs_io_Http_uri                                             89
#define ES_ejs_io_Http_set_uri                                         90
#define ES_ejs_io_Http_write                                           91
#define ES_ejs_io_Http_NUM_CLASS_PROP                                  92

/**
 * Instance slots for "Http" type 
 */
#define ES_ejs_io_Http_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type Http 
 */
#define ES_ejs_io_Http_Http_uri                                        0
#define ES_ejs_io_Http_addRequestHeader_key                            0
#define ES_ejs_io_Http_addRequestHeader_value                          1
#define ES_ejs_io_Http_addRequestHeader_overwrite                      2
#define ES_ejs_io_Http_set_callback_cb                                 0
#define ES_ejs_io_Http_close_graceful                                  0
#define ES_ejs_io_Http_set_certificateFile_certFile                    0
#define ES_ejs_io_Http_del_uri                                         0
#define ES_ejs_io_Http_set_followRedirects_flag                        0
#define ES_ejs_io_Http_form_uri                                        0
#define ES_ejs_io_Http_form_postData                                   1
#define ES_ejs_io_Http_get_uri                                         0
#define ES_ejs_io_Http_head_uri                                        0
#define ES_ejs_io_Http_header_key                                      0
#define ES_ejs_io_Http_set_keyFile_keyFile                             0
#define ES_ejs_io_Http_set_method_name                                 0
#define ES_ejs_io_Http_post_uri                                        0
#define ES_ejs_io_Http_post_data                                       1
#define ES_ejs_io_Http_set_postLength_length                           0
#define ES_ejs_io_Http_set_postData_items                              0
#define ES_ejs_io_Http_put_uri                                         0
#define ES_ejs_io_Http_put_putData                                     1
#define ES_ejs_io_Http_read_buffer                                     0
#define ES_ejs_io_Http_read_offset                                     1
#define ES_ejs_io_Http_read_count                                      2
#define ES_ejs_io_Http_readString_count                                0
#define ES_ejs_io_Http_readLines_count                                 0
#define ES_ejs_io_Http_setCredentials_username                         0
#define ES_ejs_io_Http_setCredentials_password                         1
#define ES_ejs_io_Http_set_timeout_timeout                             0
#define ES_ejs_io_Http_upload_uri                                      0
#define ES_ejs_io_Http_upload_filename                                 1
#define ES_ejs_io_Http_set_uri_uriString                               0
#define ES_ejs_io_Http_write_data                                      0


/**
 *   Class property slots for the "HttpDataEvent" class 
 */
#define ES_ejs_io_HttpDataEvent__origin                                10
#define ES_ejs_io_HttpDataEvent_HttpDataEvent                          10
#define ES_ejs_io_HttpDataEvent__initializer__HttpDataEvent_initializer 11
#define ES_ejs_io_HttpDataEvent_NUM_CLASS_PROP                         12

/**
 * Instance slots for "HttpDataEvent" type 
 */
#define ES_ejs_io_HttpDataEvent_NUM_INSTANCE_PROP                      4


/**
 *   Class property slots for the "HttpErrorEvent" class 
 */
#define ES_ejs_io_HttpErrorEvent__origin                               10
#define ES_ejs_io_HttpErrorEvent_HttpErrorEvent                        10
#define ES_ejs_io_HttpErrorEvent__initializer__HttpErrorEvent_initializer 11
#define ES_ejs_io_HttpErrorEvent_NUM_CLASS_PROP                        12

/**
 * Instance slots for "HttpErrorEvent" type 
 */
#define ES_ejs_io_HttpErrorEvent_NUM_INSTANCE_PROP                     4


/**
 *   Class property slots for the "TextStream" class 
 */
#define ES_ejs_io_TextStream__origin                                   5
#define ES_ejs_io_TextStream_TextStream                                5
#define ES_ejs_io_TextStream__initializer__TextStream_initializer      6
#define ES_ejs_io_TextStream_LATIN1                                    7
#define ES_ejs_io_TextStream_UTF_8                                     8
#define ES_ejs_io_TextStream_UTF_16                                    9
#define ES_ejs_io_TextStream_close                                     10
#define ES_ejs_io_TextStream_encoding                                  11
#define ES_ejs_io_TextStream_set_encoding                              12
#define ES_ejs_io_TextStream_fill                                      13
#define ES_ejs_io_TextStream_flush                                     14
#define ES_ejs_io_TextStream_read                                      15
#define ES_ejs_io_TextStream_readLine                                  16
#define ES_ejs_io_TextStream_readLines                                 17
#define ES_ejs_io_TextStream_readString                                18
#define ES_ejs_io_TextStream_write                                     19
#define ES_ejs_io_TextStream_writeLine                                 20
#define ES_ejs_io_TextStream_NUM_CLASS_PROP                            21

/**
 * Instance slots for "TextStream" type 
 */
#define ES_ejs_io_TextStream_newline                                   0
#define ES_ejs_io_TextStream_inbuf                                     1
#define ES_ejs_io_TextStream_format                                    2
#define ES_ejs_io_TextStream_nextStream                                3
#define ES_ejs_io_TextStream_NUM_INSTANCE_PROP                         4

/**
 * 
 *    Local slots for methods in type TextStream 
 */
#define ES_ejs_io_TextStream_TextStream_stream                         0
#define ES_ejs_io_TextStream_close_graceful                            0
#define ES_ejs_io_TextStream_set_encoding_encoding                     0
#define ES_ejs_io_TextStream_fill_was                                  0
#define ES_ejs_io_TextStream_read_buffer                               0
#define ES_ejs_io_TextStream_read_offset                               1
#define ES_ejs_io_TextStream_read_count                                2
#define ES_ejs_io_TextStream_read_total                                3
#define ES_ejs_io_TextStream_read_where                                4
#define ES_ejs_io_TextStream_read__hoisted_5_len                       5
#define ES_ejs_io_TextStream_readLine_start                            0
#define ES_ejs_io_TextStream_readLine__hoisted_1_c                     1
#define ES_ejs_io_TextStream_readLine__hoisted_2_i                     2
#define ES_ejs_io_TextStream_readLines_numLines                        0
#define ES_ejs_io_TextStream_readLines_result                          1
#define ES_ejs_io_TextStream_readLines__hoisted_2_i                    2
#define ES_ejs_io_TextStream_readString_count                          0
#define ES_ejs_io_TextStream_write_data                                0
#define ES_ejs_io_TextStream_writeLine_lines                           0
#define ES_ejs_io_TextStream_writeLine_written                         1
#define ES_ejs_io_TextStream_writeLine_count                           2
#define ES_ejs_io_TextStream_writeLine__hoisted_3_line                 3


/**
 *   Class property slots for the "XMLHttp" class 
 */
#define ES_ejs_io_XMLHttp__origin                                      5
#define ES_ejs_io_XMLHttp_XMLHttp                                      5
#define ES_ejs_io_XMLHttp__initializer__XMLHttp_initializer            6
#define ES_ejs_io_XMLHttp_Uninitialized                                7
#define ES_ejs_io_XMLHttp_Open                                         8
#define ES_ejs_io_XMLHttp_Sent                                         9
#define ES_ejs_io_XMLHttp_Receiving                                    10
#define ES_ejs_io_XMLHttp_Loaded                                       11
#define ES_ejs_io_XMLHttp_abort                                        12
#define ES_ejs_io_XMLHttp_http                                         13
#define ES_ejs_io_XMLHttp_readyState                                   14
#define ES_ejs_io_XMLHttp_responseText                                 15
#define ES_ejs_io_XMLHttp_responseXML                                  16
#define ES_ejs_io_XMLHttp_responseBody                                 17
#define ES_ejs_io_XMLHttp_status                                       18
#define ES_ejs_io_XMLHttp_statusText                                   19
#define ES_ejs_io_XMLHttp_getAllResponseHeaders                        20
#define ES_ejs_io_XMLHttp_getResponseHeader                            21
#define ES_ejs_io_XMLHttp_open                                         22
#define ES_ejs_io_XMLHttp_send                                         23
#define ES_ejs_io_XMLHttp_setRequestHeader                             24
#define ES_ejs_io_XMLHttp_callback                                     25
#define ES_ejs_io_XMLHttp_notify                                       26
#define ES_ejs_io_XMLHttp_NUM_CLASS_PROP                               27

/**
 * Instance slots for "XMLHttp" type 
 */
#define ES_ejs_io_XMLHttp_hp                                           0
#define ES_ejs_io_XMLHttp_state                                        1
#define ES_ejs_io_XMLHttp_response                                     2
#define ES_ejs_io_XMLHttp_onreadystatechange                           3
#define ES_ejs_io_XMLHttp_NUM_INSTANCE_PROP                            4

/**
 * 
 *    Local slots for methods in type XMLHttp 
 */
#define ES_ejs_io_XMLHttp_getAllResponseHeaders_result                 0
#define ES_ejs_io_XMLHttp_getAllResponseHeaders__hoisted_1_key         1
#define ES_ejs_io_XMLHttp_getResponseHeader_key                        0
#define ES_ejs_io_XMLHttp_open_method                                  0
#define ES_ejs_io_XMLHttp_open_url                                     1
#define ES_ejs_io_XMLHttp_open_async                                   2
#define ES_ejs_io_XMLHttp_open_user                                    3
#define ES_ejs_io_XMLHttp_open_password                                4
#define ES_ejs_io_XMLHttp_open__hoisted_5_timeout                      5
#define ES_ejs_io_XMLHttp_open__hoisted_6_when                         6
#define ES_ejs_io_XMLHttp_send_content                                 0
#define ES_ejs_io_XMLHttp_setRequestHeader_key                         0
#define ES_ejs_io_XMLHttp_setRequestHeader_value                       1
#define ES_ejs_io_XMLHttp_callback_e                                   0
#define ES_ejs_io_XMLHttp_callback_hp                                  1
#define ES_ejs_io_XMLHttp_callback_count                               2

#define _ES_CHECKSUM_ejs_io 1375797

#endif
