#
#	Makefile for the Ejscript web framework gatways and embeddings
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#
include 		.makedep

#	TODO - really need to be able to apply flags to just one target
MAKE_IFLAGS		+=	$(BLD_APPWEB_IFLAGS)
