/*
 * Sample.slots.h -- Property slot definitions for the "Sample" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 0.9.8.
 */

#ifndef _h_SLOTS_SampleSlots
#define _h_SLOTS_SampleSlots 1


/**
 * Slots for the "Sample" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */


/**
 *   Class property slots for the "Shape" class 
 */
#define ES_Sample_Shape__origin                                        5
#define ES_Sample_Shape_Shape                                          5
#define ES_Sample_Shape_area                                           6
#define ES_Sample_Shape_moveTo                                         7
#define ES_Sample_Shape_NUM_CLASS_PROP                                 8

/**
 * Instance slots for "Shape" type 
 */
#define ES_Sample_Shape_x                                              0
#define ES_Sample_Shape_y                                              1
#define ES_Sample_Shape_height                                         2
#define ES_Sample_Shape_width                                          3
#define ES_Sample_Shape_NUM_INSTANCE_PROP                              4

/**
 * 
 *    Local slots for methods in type Shape 
 */
#define ES_Sample_Shape_Shape_height                                   0
#define ES_Sample_Shape_Shape_width                                    1
#define ES_Sample_Shape_moveTo_x                                       0
#define ES_Sample_Shape_moveTo_y                                       1

#define _ES_CHECKSUM_Sample 41497

#endif
