#!/bin/bash
#
# 	postinst -- Post installation script for !!BLD_PRODUCT!!
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_PREFIX=!!BLD_PREFIX!!
BLD_DOC_PREFIX=!!BLD_DOC_PREFIX!!
BLD_SAM_PREFIX=!!BLD_SAM_PREFIX!!
BLD_SRC_PREFIX=!!BLD_SRC_PREFIX!!

###############################################################################
#
#	Initialization
#

setup() {
	:
}


#
#	Configure the product service
#
#	Usage:	configureService start|stop|install
#
configureService() {
	local action=$1

	case $action in

	start|stop)
		;;

	install)
		;;
	esac
}



# 
# 	Execute the install
#
install() {

	configureService install
	configureService start
}


#
#	Main
#
cd /
action=$1

case $action in
	configure)							# when new
		oldVersion=$2
		install
		echo -e "\n$BLD_NAME installation successful."
		;;
	abort-upgrade)						# when old
		;;
	abort-remove)
		;;
esac

exit 0
