#
#	Makefile to build the Ejscript core system classes
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

include 		.makedep

ifeq			($(BLD_FEATURE_DECIMAL),1)
POST_DIRS		+= decimal
endif

