#!/bin/bash
#
# 	postrm -- Post removal script for !!BLD_PRODUCT!!-src
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_PREFIX=!!BLD_PREFIX!!
BLD_DOC_PREFIX=!!BLD_DOC_PREFIX!!
BLD_SAM_PREFIX=!!BLD_SAM_PREFIX!!
BLD_SRC_PREFIX=!!BLD_SRC_PREFIX!!

###############################################################################

remove() {
	:
}


purge() {
	:
}

#
#	Main
#
action=$1
cd /

case $action in
	remove)					# when new
		remove
		;;
	purge)					# when new
		purge
		;;
	failed-upgrade)			# when new
		oldVersion=$2
		;;
	abort-upgrade)			# when new
		oldVersion=$2
		;;
	upgrade)				# when old
		newVersion=$2
		;;
	disappear)				# when disappearing
		# disappear overwriter overwriter-version
		;;
esac

echo
echo "$BLD_NAME $action successful"

exit 0
