/*
 * ejs.sys.slots.h -- Property slot definitions for the "ejs.sys" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 0.9.8.
 */

#ifndef _h_SLOTS_EjsSysSlots
#define _h_SLOTS_EjsSysSlots 1


/**
 * Slots for the "ejs.sys" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "App" class 
 */
#define ES_ejs_sys_App__origin                                         5
#define ES_ejs_sys_App__initializer__App_initializer                   5
#define ES_ejs_sys_App_UTF_8                                           6
#define ES_ejs_sys_App_UTF_16                                          7
#define ES_ejs_sys_App_args                                            8
#define ES_ejs_sys_App_dir                                             9
#define ES_ejs_sys_App_getEnv                                          10
#define ES_ejs_sys_App_exit                                            11
#define ES_ejs_sys_App_name                                            12
#define ES_ejs_sys_App_noexit                                          13
#define ES_ejs_sys_App_serviceEvents                                   14
#define ES_ejs_sys_App_sleep                                           15
#define ES_ejs_sys_App_title                                           16
#define ES_ejs_sys_App_version                                         17
#define ES_ejs_sys_App_workingDir                                      18
#define ES_ejs_sys_App_set_workingDir                                  19
#define ES_ejs_sys_App_NUM_CLASS_PROP                                  20

/**
 * Instance slots for "App" type 
 */
#define ES_ejs_sys_App_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type App 
 */
#define ES_ejs_sys_App_getEnv_name                                     0
#define ES_ejs_sys_App_exit_status                                     0
#define ES_ejs_sys_App_noexit_exit                                     0
#define ES_ejs_sys_App_serviceEvents_count                             0
#define ES_ejs_sys_App_serviceEvents_timeout                           1
#define ES_ejs_sys_App_sleep_delay                                     0
#define ES_ejs_sys_App_set_workingDir_value                            0


/**
 *   Class property slots for the "Config" class 
 */
#define ES_ejs_sys_Config__origin                                      5
#define ES_ejs_sys_Config_Debug                                        5
#define ES_ejs_sys_Config_CPU                                          6
#define ES_ejs_sys_Config_DB                                           7
#define ES_ejs_sys_Config_E4X                                          8
#define ES_ejs_sys_Config_Floating                                     9
#define ES_ejs_sys_Config_Http                                         10
#define ES_ejs_sys_Config_Lang                                         11
#define ES_ejs_sys_Config_Legacy                                       12
#define ES_ejs_sys_Config_Multithread                                  13
#define ES_ejs_sys_Config_NumberType                                   14
#define ES_ejs_sys_Config_OS                                           15
#define ES_ejs_sys_Config_Product                                      16
#define ES_ejs_sys_Config_RegularExpressions                           17
#define ES_ejs_sys_Config_Title                                        18
#define ES_ejs_sys_Config_Version                                      19
#define ES_ejs_sys_Config_LibDir                                       20
#define ES_ejs_sys_Config_BinDir                                       21
#define ES_ejs_sys_Config_NUM_CLASS_PROP                               22

/**
 * Instance slots for "Config" type 
 */
#define ES_ejs_sys_Config_NUM_INSTANCE_PROP                            0


/**
 *   Class property slots for the "GC" class 
 */
#define ES_ejs_sys_GC__origin                                          5
#define ES_ejs_sys_GC_allocatedMemory                                  5
#define ES_ejs_sys_GC_enabled                                          6
#define ES_ejs_sys_GC_set_enabled                                      7
#define ES_ejs_sys_GC_maxMemory                                        8
#define ES_ejs_sys_GC_set_maxMemory                                    9
#define ES_ejs_sys_GC_printStats                                       10
#define ES_ejs_sys_GC_peakMemory                                       11
#define ES_ejs_sys_GC_workQuota                                        12
#define ES_ejs_sys_GC_set_workQuota                                    13
#define ES_ejs_sys_GC_run                                              14
#define ES_ejs_sys_GC_NUM_CLASS_PROP                                   15

/**
 * Instance slots for "GC" type 
 */
#define ES_ejs_sys_GC_NUM_INSTANCE_PROP                                0

/**
 * 
 *    Local slots for methods in type GC 
 */
#define ES_ejs_sys_GC_set_enabled_on                                   0
#define ES_ejs_sys_GC_set_maxMemory_limit                              0
#define ES_ejs_sys_GC_set_workQuota_quota                              0
#define ES_ejs_sys_GC_run_deep                                         0


/**
 *   Class property slots for the "Memory" class 
 */
#define ES_ejs_sys_Memory__origin                                      5
#define ES_ejs_sys_Memory_printStats                                   5
#define ES_ejs_sys_Memory_NUM_CLASS_PROP                               6

/**
 * Instance slots for "Memory" type 
 */
#define ES_ejs_sys_Memory_NUM_INSTANCE_PROP                            0


/**
 *   Class property slots for the "System" class 
 */
#define ES_ejs_sys_System__origin                                      5
#define ES_ejs_sys_System__initializer__System_initializer             5
#define ES_ejs_sys_System_Bufsize                                      6
#define ES_ejs_sys_System_hostname                                     7
#define ES_ejs_sys_System_run                                          8
#define ES_ejs_sys_System_runx                                         9
#define ES_ejs_sys_System_NUM_CLASS_PROP                               10

/**
 * Instance slots for "System" type 
 */
#define ES_ejs_sys_System_NUM_INSTANCE_PROP                            0

/**
 * 
 *    Local slots for methods in type System 
 */
#define ES_ejs_sys_System_hostname_fullyQualified                      0
#define ES_ejs_sys_System_run_cmd                                      0
#define ES_ejs_sys_System_runx_cmd                                     0

#define _ES_CHECKSUM_ejs_sys 255705

#endif
