/*
 * ejs.slots.h -- Property slot definitions for the "ejs" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 0.9.8.
 */

#ifndef _h_SLOTS_EjsSlots
#define _h_SLOTS_EjsSlots 1


/**
 * Slots for the "ejs" module 
 */


/**
 *   Class property slots for the "global" class 
 */
#define ES_Object                                                      0
#define ES_Boolean                                                     1
#define ES_Null                                                        2
#define ES_Number                                                      3
#define ES_String                                                      4
#define ES_Void                                                        5
#define ES_Function                                                    6
#define ES_Array                                                       7
#define ES_Block                                                       8
#define ES_ByteArray                                                   9
#define ES_Date                                                        10
#define ES_ArgError                                                    11
#define ES_ArithmeticError                                             12
#define ES_AssertError                                                 13
#define ES_InstructionError                                            14
#define ES_Error                                                       15
#define ES_IOError                                                     16
#define ES_InternalError                                               17
#define ES_MemoryError                                                 18
#define ES_OutOfBoundsError                                            19
#define ES_ReferenceError                                              20
#define ES_ResourceError                                               21
#define ES_StateError                                                  22
#define ES_SyntaxError                                                 23
#define ES_TypeError                                                   24
#define ES_URIError                                                    25
#define ES_Iterable                                                    26
#define ES_Iterator                                                    27
#define ES_JSON                                                        28
#define ES_Namespace                                                   29
#define ES_Reflect                                                     30
#define ES_typeOf                                                      31
#define ES_RegExp                                                      32
#define ES_Stream                                                      33
#define ES_Type                                                        34
#define ES_public                                                      35
#define ES_internal                                                    36
#define ES_intrinsic                                                   37
#define ES_iterator                                                    38
#define ES_CONFIG                                                      39
#define ES_TODO                                                        40
#define ES_FUTURE                                                      41
#define ES_ASC                                                         42
#define ES_DOC_ONLY                                                    43
#define ES_DEPRECATED                                                  44
#define ES_REGEXP                                                      45
#define ES_boolean                                                     46
#define ES_double                                                      47
#define ES_num                                                         48
#define ES_string                                                      49
#define ES_false                                                       50
#define ES_global                                                      51
#define ES_null                                                        52
#define ES_Infinity                                                    53
#define ES_NegativeInfinity                                            54
#define ES_NaN                                                         55
#define ES_StopIteration                                               56
#define ES_true                                                        57
#define ES_undefined                                                   58
#define ES_void                                                        59
#define ES_assert                                                      60
#define ES_breakpoint                                                  61
#define ES_cloneBase                                                   62
#define ES_deserialize                                                 63
#define ES_dump                                                        64
#define ES_eprint                                                      65
#define ES_formatStack                                                 66
#define ES_hashcode                                                    67
#define ES_load                                                        68
#define ES_print                                                       69
#define ES_printv                                                      70
#define ES_parse                                                       71
#define ES_serialize                                                   72
#define ES_printHash                                                   73
#define ES_ejs_events_Event                                            74
#define ES_ejs_events_Dispatcher                                       75
#define ES_Endpoint                                                    76
#define ES_ejs_events_Timer                                            77
#define ES_ejs_events_TimerEvent                                       78
#define ES_XML                                                         79
#define ES_XMLList                                                     80
#define ES_ejs_io_BinaryStream                                         81
#define ES_ejs_io_File                                                 82
#define ES_ejs_io_Http                                                 83
#define ES_ejs_io_HttpDataEvent                                        84
#define ES_ejs_io_HttpErrorEvent                                       85
#define ES_ejs_io_TextStream                                           86
#define ES_ejs_io_XMLHttp                                              87
#define ES_ejs_sys_App                                                 88
#define ES_Config                                                      89
#define ES_ejs_sys_GC                                                  90
#define ES_ejs_sys_Memory                                              91
#define ES_ejs_sys_System                                              92
#define ES_basename                                                    93
#define ES_close                                                       94
#define ES_cp                                                          95
#define ES_dirname                                                     96
#define ES_exists                                                      97
#define ES_extension                                                   98
#define ES_freeSpace                                                   99
#define ES_isDir                                                       100
#define ES_ls                                                          101
#define ES_mkdir                                                       102
#define ES_mv                                                          103
#define ES_open                                                        104
#define ES_pwd                                                         105
#define ES_read                                                        106
#define ES_rm                                                          107
#define ES_rmdir                                                       108
#define ES_tempname                                                    109
#define ES_write                                                       110
#define ES_global_NUM_CLASS_PROP                                       111

/**
 * Instance slots for "global" type 
 */
#define ES_global_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type global 
 */
#define ES_typeOf_o                                                    0
#define ES_assert_condition                                            0
#define ES_cloneBase_klass                                             0
#define ES_deserialize_obj                                             0
#define ES_dump_args                                                   0
#define ES_dump_e                                                      1
#define ES_eprint_args                                                 0
#define ES_hashcode_o                                                  0
#define ES_load_file                                                   0
#define ES_print_args                                                  0
#define ES_printv_args                                                 0
#define ES_parse_input                                                 0
#define ES_parse_preferredType                                         1
#define ES_serialize_obj                                               0
#define ES_serialize_maxDepth                                          1
#define ES_serialize_all                                               2
#define ES_serialize_base                                              3
#define ES_printHash_name                                              0
#define ES_printHash_o                                                 1
#define ES_basename_path                                               0
#define ES_close_file                                                  0
#define ES_close_graceful                                              1
#define ES_cp_fromPath                                                 0
#define ES_cp_toPath                                                   1
#define ES_dirname_path                                                0
#define ES_exists_path                                                 0
#define ES_extension_path                                              0
#define ES_freeSpace_path                                              0
#define ES_isDir_path                                                  0
#define ES_ls_path                                                     0
#define ES_ls_enumDirs                                                 1
#define ES_mkdir_path                                                  0
#define ES_mkdir_permissions                                           1
#define ES_mv_fromFile                                                 0
#define ES_mv_toFile                                                   1
#define ES_open_path                                                   0
#define ES_open_mode                                                   1
#define ES_open_permissions                                            2
#define ES_open_file                                                   3
#define ES_read_file                                                   0
#define ES_read_count                                                  1
#define ES_rm_path                                                     0
#define ES_rmdir_path                                                  0
#define ES_rmdir_recursive                                             1
#define ES_tempname_directory                                          0
#define ES_write_file                                                  0
#define ES_write_items                                                 1


/**
 *   Class property slots for the "Object" class 
 */
#define ES_Object__origin                                              0
#define ES_Object_clone                                                0
#define ES_Object_get                                                  1
#define ES_Object_getValues                                            2
#define ES_Object_length                                               3
#define ES_Object_toString                                             4
#define ES_Object_NUM_CLASS_PROP                                       5

/**
 * Instance slots for "Object" type 
 */
#define ES_Object_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type Object 
 */
#define ES_Object_clone_deep                                           0
#define ES_Object_get_deep                                             0
#define ES_Object_get_namespaces                                       1
#define ES_Object_getValues_deep                                       0
#define ES_Object_getValues_namespaces                                 1
#define ES_Object_toString_locale                                      0


/**
 *   Class property slots for the "Boolean" class 
 */
#define ES_Boolean__origin                                             5
#define ES_Boolean_Boolean                                             5
#define ES_Boolean_NUM_CLASS_PROP                                      6

/**
 * Instance slots for "Boolean" type 
 */
#define ES_Boolean_NUM_INSTANCE_PROP                                   0

/**
 * 
 *    Local slots for methods in type Boolean 
 */
#define ES_Boolean_Boolean_value                                       0


/**
 *   Class property slots for the "Null" class 
 */
#define ES_Null__origin                                                5
#define ES_Null_NUM_CLASS_PROP                                         5

/**
 * Instance slots for "Null" type 
 */
#define ES_Null_NUM_INSTANCE_PROP                                      0


/**
 *   Class property slots for the "Number" class 
 */
#define ES_Number__origin                                              5
#define ES_Number_Number                                               5
#define ES_Number__initializer__Number_initializer                     6
#define ES_Number_MaxValue                                             7
#define ES_Number_MinValue                                             8
#define ES_Number_ceil                                                 9
#define ES_Number_floor                                                10
#define ES_Number_isFinite                                             11
#define ES_Number_isNaN                                                12
#define ES_Number_round                                                13
#define ES_Number_toFixed                                              14
#define ES_Number_toPrecision                                          15
#define ES_Number_abs                                                  16
#define ES_Number_max                                                  17
#define ES_Number_min                                                  18
#define ES_Number_power                                                19
#define ES_Number_NUM_CLASS_PROP                                       20

/**
 * Instance slots for "Number" type 
 */
#define ES_Number_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type Number 
 */
#define ES_Number_Number_value                                         0
#define ES_Number_toFixed_fractionDigits                               0
#define ES_Number_toPrecision_numDigits                                0
#define ES_Number_max_other                                            0
#define ES_Number_min_other                                            0
#define ES_Number_power_power                                          0
#define ES_Number_power_result                                         1
#define ES_Number_power__hoisted_2_i                                   2


/**
 *   Class property slots for the "String" class 
 */
#define ES_String__origin                                              5
#define ES_String_String                                               5
#define ES_String_caseCompare                                          6
#define ES_String_charAt                                               7
#define ES_String_charCodeAt                                           8
#define ES_String_concat                                               9
#define ES_String_contains                                             10
#define ES_String_endsWith                                             11
#define ES_String_format                                               12
#define ES_String_fromCharCode                                         13
#define ES_String_indexOf                                              14
#define ES_String_isDigit                                              15
#define ES_String_isAlpha                                              16
#define ES_String_isLower                                              17
#define ES_String_isSpace                                              18
#define ES_String_isUpper                                              19
#define ES_String_lastIndexOf                                          20
#define ES_String_match                                                21
#define ES_String_toCamel                                              22
#define ES_String_toPascal                                             23
#define ES_String_printable                                            24
#define ES_String_quote                                                25
#define ES_String_remove                                               26
#define ES_String_replace                                              27
#define ES_String_reverse                                              28
#define ES_String_search                                               29
#define ES_String_slice                                                30
#define ES_String_split                                                31
#define ES_String_startsWith                                           32
#define ES_String_substring                                            33
#define ES_String_times                                                34
#define ES_String_tokenize                                             35
#define ES_String_toLower                                              36
#define ES_String_toUpper                                              37
#define ES_String_trim                                                 38
#define ES_String_MINUS                                                39
#define ES_String_MOD                                                  40
#define ES_String_NUM_CLASS_PROP                                       41

/**
 * Instance slots for "String" type 
 */
#define ES_String_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type String 
 */
#define ES_String_String_str                                           0
#define ES_String_caseCompare_compare                                  0
#define ES_String_charAt_index                                         0
#define ES_String_charCodeAt_index                                     0
#define ES_String_concat_args                                          0
#define ES_String_contains_pattern                                     0
#define ES_String_endsWith_test                                        0
#define ES_String_format_args                                          0
#define ES_String_fromCharCode_codes                                   0
#define ES_String_indexOf_pattern                                      0
#define ES_String_indexOf_startIndex                                   1
#define ES_String_lastIndexOf_pattern                                  0
#define ES_String_lastIndexOf_location                                 1
#define ES_String_match_pattern                                        0
#define ES_String_remove_start                                         0
#define ES_String_remove_end                                           1
#define ES_String_replace_pattern                                      0
#define ES_String_replace_replacement                                  1
#define ES_String_search_pattern                                       0
#define ES_String_slice_start                                          0
#define ES_String_slice_end                                            1
#define ES_String_slice_step                                           2
#define ES_String_split_delimiter                                      0
#define ES_String_split_limit                                          1
#define ES_String_startsWith_test                                      0
#define ES_String_substring_startIndex                                 0
#define ES_String_substring_end                                        1
#define ES_String_times_times                                          0
#define ES_String_times_s                                              1
#define ES_String_times__hoisted_2_i                                   2
#define ES_String_tokenize_format                                      0
#define ES_String_toLower_locale                                       0
#define ES_String_toUpper_locale                                       0
#define ES_String_trim_str                                             0
#define ES_String_MINUS_str                                            0
#define ES_String_MINUS_i                                              1
#define ES_String_MOD_obj                                              0


/**
 *   Class property slots for the "Void" class 
 */
#define ES_Void__origin                                                5
#define ES_Void_NUM_CLASS_PROP                                         5

/**
 * Instance slots for "Void" type 
 */
#define ES_Void_NUM_INSTANCE_PROP                                      0


/**
 *   Class property slots for the "Function" class 
 */
#define ES_Function__origin                                            5
#define ES_Function_apply                                              5
#define ES_Function_call                                               6
#define ES_Function_NUM_CLASS_PROP                                     7

/**
 * Instance slots for "Function" type 
 */
#define ES_Function_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type Function 
 */
#define ES_Function_apply_thisObject                                   0
#define ES_Function_apply_args                                         1
#define ES_Function_call_thisObject                                    0
#define ES_Function_call_args                                          1


/**
 *   Class property slots for the "Array" class 
 */
#define ES_Array__origin                                               5
#define ES_Array_Array                                                 5
#define ES_Array_append                                                6
#define ES_Array_clear                                                 7
#define ES_Array_compact                                               8
#define ES_Array_concat                                                9
#define ES_Array_contains                                              10
#define ES_Array_every                                                 11
#define ES_Array_filter                                                12
#define ES_Array_find                                                  13
#define ES_Array_findAll                                               14
#define ES_Array_forEach                                               15
#define ES_Array_indexOf                                               16
#define ES_Array_insert                                                17
#define ES_Array_join                                                  18
#define ES_Array_lastIndexOf                                           19
#define ES_Array_set_length                                            20
#define ES_Array_map                                                   21
#define ES_Array_pop                                                   22
#define ES_Array_push                                                  23
#define ES_Array_reject                                                24
#define ES_Array_remove                                                25
#define ES_Array_reverse                                               26
#define ES_Array_shift                                                 27
#define ES_Array_slice                                                 28
#define ES_Array_some                                                  29
#define ES_Array_sort                                                  30
#define ES_Array_splice                                                31
#define ES_Array_transform                                             32
#define ES_Array_unique                                                33
#define ES_Array_unshift                                               34
#define ES_Array_NUM_CLASS_PROP                                        35

/**
 * Instance slots for "Array" type 
 */
#define ES_Array_NUM_INSTANCE_PROP                                     0

/**
 * 
 *    Local slots for methods in type Array 
 */
#define ES_Array_Array_values                                          0
#define ES_Array_append_obj                                            0
#define ES_Array_concat_args                                           0
#define ES_Array_contains_element                                      0
#define ES_Array_every_match                                           0
#define ES_Array_every__hoisted_1_i                                    1
#define ES_Array_filter_match                                          0
#define ES_Array_find_match                                            0
#define ES_Array_find_result                                           1
#define ES_Array_find__hoisted_2_i                                     2
#define ES_Array_findAll_match                                         0
#define ES_Array_findAll_result                                        1
#define ES_Array_findAll__hoisted_2_i                                  2
#define ES_Array_forEach_modifier                                      0
#define ES_Array_forEach_thisObj                                       1
#define ES_Array_indexOf_element                                       0
#define ES_Array_indexOf_startIndex                                    1
#define ES_Array_insert_pos                                            0
#define ES_Array_insert_args                                           1
#define ES_Array_join_sep                                              0
#define ES_Array_lastIndexOf_element                                   0
#define ES_Array_lastIndexOf_fromIndex                                 1
#define ES_Array_set_length_value                                      0
#define ES_Array_map_mapper                                            0
#define ES_Array_map_result                                            1
#define ES_Array_push_items                                            0
#define ES_Array_reject_match                                          0
#define ES_Array_reject_result                                         1
#define ES_Array_reject__hoisted_2_i                                   2
#define ES_Array_remove_start                                          0
#define ES_Array_remove_end                                            1
#define ES_Array_slice_start                                           0
#define ES_Array_slice_end                                             1
#define ES_Array_slice_step                                            2
#define ES_Array_some_match                                            0
#define ES_Array_some_result                                           1
#define ES_Array_some__hoisted_2_i                                     2
#define ES_Array_sort_compare                                          0
#define ES_Array_sort_order                                            1
#define ES_Array_splice_start                                          0
#define ES_Array_splice_deleteCount                                    1
#define ES_Array_splice_values                                         2
#define ES_Array_transform_mapper                                      0
#define ES_Array_transform__hoisted_1_i                                1
#define ES_Array_unshift_items                                         0


/**
 *   Class property slots for the "Block" class 
 */
#define ES_Block__origin                                               5
#define ES_Block_NUM_CLASS_PROP                                        5

/**
 * Instance slots for "Block" type 
 */
#define ES_Block_NUM_INSTANCE_PROP                                     0


/**
 *   Class property slots for the "ByteArray" class 
 */
#define ES_ByteArray__origin                                           5
#define ES_ByteArray_ByteArray                                         5
#define ES_ByteArray__initializer__ByteArray_initializer               6
#define ES_ByteArray_LittleEndian                                      7
#define ES_ByteArray_BigEndian                                         8
#define ES_ByteArray_available                                         9
#define ES_ByteArray_close                                             10
#define ES_ByteArray_copyIn                                            11
#define ES_ByteArray_copyOut                                           12
#define ES_ByteArray_endian                                            13
#define ES_ByteArray_set_endian                                        14
#define ES_ByteArray_flush                                             15
#define ES_ByteArray_set_input                                         16
#define ES_ByteArray_input                                             17
#define ES_ByteArray_set_output                                        18
#define ES_ByteArray_output                                            19
#define ES_ByteArray_read                                              20
#define ES_ByteArray_readBoolean                                       21
#define ES_ByteArray_readByte                                          22
#define ES_ByteArray_readDate                                          23
#define ES_ByteArray_readDouble                                        24
#define ES_ByteArray_readInteger                                       25
#define ES_ByteArray_readLong                                          26
#define ES_ByteArray_readPosition                                      27
#define ES_ByteArray_set_readPosition                                  28
#define ES_ByteArray_readShort                                         29
#define ES_ByteArray_readString                                        30
#define ES_ByteArray_readXML                                           31
#define ES_ByteArray_reset                                             32
#define ES_ByteArray_room                                              33
#define ES_ByteArray_write                                             34
#define ES_ByteArray_writeByte                                         35
#define ES_ByteArray_writeShort                                        36
#define ES_ByteArray_writeDouble                                       37
#define ES_ByteArray_writeInteger                                      38
#define ES_ByteArray_writeLong                                         39
#define ES_ByteArray_writePosition                                     40
#define ES_ByteArray_set_writePosition                                 41
#define ES_ByteArray_NUM_CLASS_PROP                                    42

/**
 * Instance slots for "ByteArray" type 
 */
#define ES_ByteArray_NUM_INSTANCE_PROP                                 0

/**
 * 
 *    Local slots for methods in type ByteArray 
 */
#define ES_ByteArray_ByteArray_size                                    0
#define ES_ByteArray_ByteArray_growable                                1
#define ES_ByteArray_close_graceful                                    0
#define ES_ByteArray_copyIn_destOffset                                 0
#define ES_ByteArray_copyIn_src                                        1
#define ES_ByteArray_copyIn_srcOffset                                  2
#define ES_ByteArray_copyIn_count                                      3
#define ES_ByteArray_copyOut_srcOffset                                 0
#define ES_ByteArray_copyOut_dest                                      1
#define ES_ByteArray_copyOut_destOffset                                2
#define ES_ByteArray_copyOut_count                                     3
#define ES_ByteArray_set_endian_value                                  0
#define ES_ByteArray_set_input_value                                   0
#define ES_ByteArray_set_output_callback                               0
#define ES_ByteArray_read_buffer                                       0
#define ES_ByteArray_read_offset                                       1
#define ES_ByteArray_read_count                                        2
#define ES_ByteArray_set_readPosition_position                         0
#define ES_ByteArray_readString_count                                  0
#define ES_ByteArray_write_data                                        0
#define ES_ByteArray_writeByte_data                                    0
#define ES_ByteArray_writeShort_data                                   0
#define ES_ByteArray_writeDouble_data                                  0
#define ES_ByteArray_writeInteger_data                                 0
#define ES_ByteArray_writeLong_data                                    0
#define ES_ByteArray_set_writePosition_position                        0


/**
 *   Class property slots for the "Date" class 
 */
#define ES_Date__origin                                                5
#define ES_Date_Date                                                   5
#define ES_Date_day                                                    6
#define ES_Date_dayOfYear                                              7
#define ES_Date_date                                                   8
#define ES_Date_elapsed                                                9
#define ES_Date_fullYear                                               10
#define ES_Date_set_fullYear                                           11
#define ES_Date_format                                                 12
#define ES_Date_hours                                                  13
#define ES_Date_set_hours                                              14
#define ES_Date_milliseconds                                           15
#define ES_Date_set_milliseconds                                       16
#define ES_Date_minutes                                                17
#define ES_Date_set_minutes                                            18
#define ES_Date_month                                                  19
#define ES_Date_set_month                                              20
#define ES_Date_nextDay                                                21
#define ES_Date_now                                                    22
#define ES_Date_parseDate                                              23
#define ES_Date_seconds                                                24
#define ES_Date_set_seconds                                            25
#define ES_Date_time                                                   26
#define ES_Date_set_time                                               27
#define ES_Date_year                                                   28
#define ES_Date_set_year                                               29
#define ES_Date_NUM_CLASS_PROP                                         30

/**
 * Instance slots for "Date" type 
 */
#define ES_Date_NUM_INSTANCE_PROP                                      0

/**
 * 
 *    Local slots for methods in type Date 
 */
#define ES_Date_Date_args                                              0
#define ES_Date_set_fullYear_year                                      0
#define ES_Date_format_layout                                          0
#define ES_Date_set_hours_hour                                         0
#define ES_Date_set_milliseconds_ms                                    0
#define ES_Date_set_minutes_min                                        0
#define ES_Date_set_month_month                                        0
#define ES_Date_nextDay_inc                                            0
#define ES_Date_parseDate_arg                                          0
#define ES_Date_parseDate_defaultDate                                  1
#define ES_Date_set_seconds_sec                                        0
#define ES_Date_set_time_value                                         0
#define ES_Date_set_year_year                                          0


/**
 *   Class property slots for the "ArgError" class 
 */
#define ES_ArgError__origin                                            8
#define ES_ArgError_ArgError                                           8
#define ES_ArgError_NUM_CLASS_PROP                                     9

/**
 * Instance slots for "ArgError" type 
 */
#define ES_ArgError_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type ArgError 
 */
#define ES_ArgError_ArgError_message                                   0


/**
 *   Class property slots for the "ArithmeticError" class 
 */
#define ES_ArithmeticError__origin                                     8
#define ES_ArithmeticError_ArithmeticError                             8
#define ES_ArithmeticError_NUM_CLASS_PROP                              9

/**
 * Instance slots for "ArithmeticError" type 
 */
#define ES_ArithmeticError_NUM_INSTANCE_PROP                           0

/**
 * 
 *    Local slots for methods in type ArithmeticError 
 */
#define ES_ArithmeticError_ArithmeticError_message                     0


/**
 *   Class property slots for the "AssertError" class 
 */
#define ES_AssertError__origin                                         8
#define ES_AssertError_AssertError                                     8
#define ES_AssertError_NUM_CLASS_PROP                                  9

/**
 * Instance slots for "AssertError" type 
 */
#define ES_AssertError_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type AssertError 
 */
#define ES_AssertError_AssertError_message                             0


/**
 *   Class property slots for the "InstructionError" class 
 */
#define ES_InstructionError__origin                                    8
#define ES_InstructionError_InstructionError                           8
#define ES_InstructionError_NUM_CLASS_PROP                             9

/**
 * Instance slots for "InstructionError" type 
 */
#define ES_InstructionError_NUM_INSTANCE_PROP                          0

/**
 * 
 *    Local slots for methods in type InstructionError 
 */
#define ES_InstructionError_InstructionError_message                   0


/**
 *   Class property slots for the "Error" class 
 */
#define ES_Error__origin                                               5
#define ES_Error_Error                                                 5
#define ES_Error_code                                                  6
#define ES_Error_set_code                                              7
#define ES_Error_NUM_CLASS_PROP                                        8

/**
 * Instance slots for "Error" type 
 */
#define ES_Error_message                                               0
#define ES_Error_stack                                                 1
#define ES_Error_NUM_INSTANCE_PROP                                     2

/**
 * 
 *    Local slots for methods in type Error 
 */
#define ES_Error_Error_message                                         0
#define ES_Error_set_code_value                                        0


/**
 *   Class property slots for the "IOError" class 
 */
#define ES_IOError__origin                                             8
#define ES_IOError_IOError                                             8
#define ES_IOError_NUM_CLASS_PROP                                      9

/**
 * Instance slots for "IOError" type 
 */
#define ES_IOError_NUM_INSTANCE_PROP                                   0

/**
 * 
 *    Local slots for methods in type IOError 
 */
#define ES_IOError_IOError_message                                     0


/**
 *   Class property slots for the "InternalError" class 
 */
#define ES_InternalError__origin                                       8
#define ES_InternalError_InternalError                                 8
#define ES_InternalError_NUM_CLASS_PROP                                9

/**
 * Instance slots for "InternalError" type 
 */
#define ES_InternalError_NUM_INSTANCE_PROP                             0

/**
 * 
 *    Local slots for methods in type InternalError 
 */
#define ES_InternalError_InternalError_message                         0


/**
 *   Class property slots for the "MemoryError" class 
 */
#define ES_MemoryError__origin                                         8
#define ES_MemoryError_MemoryError                                     8
#define ES_MemoryError_NUM_CLASS_PROP                                  9

/**
 * Instance slots for "MemoryError" type 
 */
#define ES_MemoryError_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type MemoryError 
 */
#define ES_MemoryError_MemoryError_message                             0


/**
 *   Class property slots for the "OutOfBoundsError" class 
 */
#define ES_OutOfBoundsError__origin                                    8
#define ES_OutOfBoundsError_OutOfBoundsError                           8
#define ES_OutOfBoundsError_NUM_CLASS_PROP                             9

/**
 * Instance slots for "OutOfBoundsError" type 
 */
#define ES_OutOfBoundsError_NUM_INSTANCE_PROP                          0

/**
 * 
 *    Local slots for methods in type OutOfBoundsError 
 */
#define ES_OutOfBoundsError_OutOfBoundsError_message                   0


/**
 *   Class property slots for the "ReferenceError" class 
 */
#define ES_ReferenceError__origin                                      8
#define ES_ReferenceError_ReferenceError                               8
#define ES_ReferenceError_NUM_CLASS_PROP                               9

/**
 * Instance slots for "ReferenceError" type 
 */
#define ES_ReferenceError_NUM_INSTANCE_PROP                            0

/**
 * 
 *    Local slots for methods in type ReferenceError 
 */
#define ES_ReferenceError_ReferenceError_message                       0


/**
 *   Class property slots for the "ResourceError" class 
 */
#define ES_ResourceError__origin                                       8
#define ES_ResourceError_ResourceError                                 8
#define ES_ResourceError_NUM_CLASS_PROP                                9

/**
 * Instance slots for "ResourceError" type 
 */
#define ES_ResourceError_NUM_INSTANCE_PROP                             0

/**
 * 
 *    Local slots for methods in type ResourceError 
 */
#define ES_ResourceError_ResourceError_message                         0


/**
 *   Class property slots for the "StateError" class 
 */
#define ES_StateError__origin                                          8
#define ES_StateError_StateError                                       8
#define ES_StateError_NUM_CLASS_PROP                                   9

/**
 * Instance slots for "StateError" type 
 */
#define ES_StateError_NUM_INSTANCE_PROP                                0

/**
 * 
 *    Local slots for methods in type StateError 
 */
#define ES_StateError_StateError_message                               0


/**
 *   Class property slots for the "SyntaxError" class 
 */
#define ES_SyntaxError__origin                                         8
#define ES_SyntaxError_SyntaxError                                     8
#define ES_SyntaxError_NUM_CLASS_PROP                                  9

/**
 * Instance slots for "SyntaxError" type 
 */
#define ES_SyntaxError_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type SyntaxError 
 */
#define ES_SyntaxError_SyntaxError_message                             0


/**
 *   Class property slots for the "TypeError" class 
 */
#define ES_TypeError__origin                                           8
#define ES_TypeError_TypeError                                         8
#define ES_TypeError_NUM_CLASS_PROP                                    9

/**
 * Instance slots for "TypeError" type 
 */
#define ES_TypeError_NUM_INSTANCE_PROP                                 0

/**
 * 
 *    Local slots for methods in type TypeError 
 */
#define ES_TypeError_TypeError_message                                 0


/**
 *   Class property slots for the "URIError" class 
 */
#define ES_URIError__origin                                            8
#define ES_URIError_URIError                                           8
#define ES_URIError_NUM_CLASS_PROP                                     9

/**
 * Instance slots for "URIError" type 
 */
#define ES_URIError_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type URIError 
 */
#define ES_URIError_URIError_message                                   0


/**
 *   Class property slots for the "Iterable" class 
 */
#define ES_Iterable__origin                                            0
#define ES_Iterable_get                                                0
#define ES_Iterable_getValues                                          1
#define ES_Iterable_NUM_CLASS_PROP                                     2

/**
 * Instance slots for "Iterable" type 
 */
#define ES_Iterable_NUM_INSTANCE_PROP                                  0

/**
 * 
 *    Local slots for methods in type Iterable 
 */
#define ES_Iterable_get_deep                                           0
#define ES_Iterable_getValues_deep                                     0


/**
 *   Class property slots for the "Iterator" class 
 */
#define ES_Iterator__origin                                            5
#define ES_Iterator_next                                               5
#define ES_Iterator_NUM_CLASS_PROP                                     6

/**
 * Instance slots for "Iterator" type 
 */
#define ES_Iterator_NUM_INSTANCE_PROP                                  0


/**
 *   Class property slots for the "JSON" class 
 */
#define ES_JSON__origin                                                5
#define ES_JSON_parse                                                  5
#define ES_JSON_stringify                                              6
#define ES_JSON_NUM_CLASS_PROP                                         7

/**
 * Instance slots for "JSON" type 
 */
#define ES_JSON_NUM_INSTANCE_PROP                                      0

/**
 * 
 *    Local slots for methods in type JSON 
 */
#define ES_JSON_parse_data                                             0
#define ES_JSON_parse_filter                                           1
#define ES_JSON_stringify_obj                                          0
#define ES_JSON_stringify_replacer                                     1
#define ES_JSON_stringify_indent                                       2


/**
 *   Class property slots for the "Namespace" class 
 */
#define ES_Namespace__origin                                           5
#define ES_Namespace_NUM_CLASS_PROP                                    5

/**
 * Instance slots for "Namespace" type 
 */
#define ES_Namespace_name                                              0
#define ES_Namespace_uri                                               1
#define ES_Namespace_NUM_INSTANCE_PROP                                 2


/**
 *   Class property slots for the "Reflect" class 
 */
#define ES_Reflect__origin                                             5
#define ES_Reflect_Reflect                                             5
#define ES_Reflect_name                                                6
#define ES_Reflect_type                                                7
#define ES_Reflect_typeName                                            8
#define ES_Reflect_NUM_CLASS_PROP                                      9

/**
 * Instance slots for "Reflect" type 
 */
#define ES_Reflect_obj                                                 0
#define ES_Reflect_NUM_INSTANCE_PROP                                   1

/**
 * 
 *    Local slots for methods in type Reflect 
 */
#define ES_Reflect_Reflect_o                                           0


/**
 *   Class property slots for the "RegExp" class 
 */
#define ES_RegExp__origin                                              5
#define ES_RegExp_RegExp                                               5
#define ES_RegExp_lastIndex                                            6
#define ES_RegExp_set_lastIndex                                        7
#define ES_RegExp_exec                                                 8
#define ES_RegExp_global                                               9
#define ES_RegExp_ignoreCase                                           10
#define ES_RegExp_multiline                                            11
#define ES_RegExp_source                                               12
#define ES_RegExp_matched                                              13
#define ES_RegExp_replace                                              14
#define ES_RegExp_split                                                15
#define ES_RegExp_start                                                16
#define ES_RegExp_sticky                                               17
#define ES_RegExp_test                                                 18
#define ES_RegExp_NUM_CLASS_PROP                                       19

/**
 * Instance slots for "RegExp" type 
 */
#define ES_RegExp_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type RegExp 
 */
#define ES_RegExp_RegExp_pattern                                       0
#define ES_RegExp_RegExp_flags                                         1
#define ES_RegExp_set_lastIndex_value                                  0
#define ES_RegExp_exec_str                                             0
#define ES_RegExp_exec_start                                           1
#define ES_RegExp_replace_str                                          0
#define ES_RegExp_replace_replacement                                  1
#define ES_RegExp_split_target                                         0
#define ES_RegExp_test_str                                             0


/**
 *   Class property slots for the "Stream" class 
 */
#define ES_Stream__origin                                              0
#define ES_Stream_close                                                0
#define ES_Stream_flush                                                1
#define ES_Stream_read                                                 2
#define ES_Stream_write                                                3
#define ES_Stream_NUM_CLASS_PROP                                       4

/**
 * Instance slots for "Stream" type 
 */
#define ES_Stream_NUM_INSTANCE_PROP                                    0

/**
 * 
 *    Local slots for methods in type Stream 
 */
#define ES_Stream_close_graceful                                       0
#define ES_Stream_read_buffer                                          0
#define ES_Stream_read_offset                                          1
#define ES_Stream_read_count                                           2
#define ES_Stream_write_data                                           0


/**
 *   Class property slots for the "Type" class 
 */
#define ES_Type__origin                                                5
#define ES_Type_NUM_CLASS_PROP                                         5

/**
 * Instance slots for "Type" type 
 */
#define ES_Type_NUM_INSTANCE_PROP                                      0


/**
 *   Class property slots for the "StopIteration" class 
 */
#define ES_StopIteration__origin                                       5
#define ES_StopIteration_NUM_CLASS_PROP                                5

/**
 * Instance slots for "StopIteration" type 
 */
#define ES_StopIteration_NUM_INSTANCE_PROP                             0


/**
 *   Class property slots for the "XML" class 
 */
#define ES_XML__origin                                                 5
#define ES_XML_XML                                                     5
#define ES_XML_load                                                    6
#define ES_XML_save                                                    7
#define ES_XML_ignoreComments                                          8
#define ES_XML_ignoreProcessingInstructions                            9
#define ES_XML_ignoreWhitespace                                        10
#define ES_XML_prettyPrinting                                          11
#define ES_XML_prettyIndent                                            12
#define ES_XML_addNamespace                                            13
#define ES_XML_appendChild                                             14
#define ES_XML_attribute                                               15
#define ES_XML_attributes                                              16
#define ES_XML_child                                                   17
#define ES_XML_childIndex                                              18
#define ES_XML_children                                                19
#define ES_XML_comments                                                20
#define ES_XML_contains                                                21
#define ES_XML_copy                                                    22
#define ES_XML_defaultSettings                                         23
#define ES_XML_descendants                                             24
#define ES_XML_elements                                                25
#define ES_XML_hasComplexContent                                       26
#define ES_XML_hasSimpleContent                                        27
#define ES_XML_inScopeNamespaces                                       28
#define ES_XML_insertChildAfter                                        29
#define ES_XML_insertChildBefore                                       30
#define ES_XML_localName                                               31
#define ES_XML_name                                                    32
#define ES_XML_namespace                                               33
#define ES_XML_namespaceDeclarations                                   34
#define ES_XML_nodeKind                                                35
#define ES_XML_normalize                                               36
#define ES_XML_parent                                                  37
#define ES_XML_prependChild                                            38
#define ES_XML_processingInstructions                                  39
#define ES_XML_replace                                                 40
#define ES_XML_setChildren                                             41
#define ES_XML_setLocalName                                            42
#define ES_XML_setName                                                 43
#define ES_XML_settings                                                44
#define ES_XML_setSettings                                             45
#define ES_XML_text                                                    46
#define ES_XML_toXMLString                                             47
#define ES_XML_NUM_CLASS_PROP                                          48

/**
 * Instance slots for "XML" type 
 */
#define ES_XML_NUM_INSTANCE_PROP                                       0

/**
 * 
 *    Local slots for methods in type XML 
 */
#define ES_XML_XML_value                                               0
#define ES_XML_load_filename                                           0
#define ES_XML_save_filename                                           0
#define ES_XML_addNamespace_ns                                         0
#define ES_XML_appendChild_child                                       0
#define ES_XML_attribute_name                                          0
#define ES_XML_child_name                                              0
#define ES_XML_contains_obj                                            0
#define ES_XML_descendants_name                                        0
#define ES_XML_elements_name                                           0
#define ES_XML_insertChildAfter_marker                                 0
#define ES_XML_insertChildAfter_child                                  1
#define ES_XML_insertChildBefore_marker                                0
#define ES_XML_insertChildBefore_child                                 1
#define ES_XML_namespace_prefix                                        0
#define ES_XML_prependChild_child                                      0
#define ES_XML_processingInstructions_name                             0
#define ES_XML_replace_property                                        0
#define ES_XML_replace_value                                           1
#define ES_XML_setChildren_properties                                  0
#define ES_XML_setLocalName_name                                       0
#define ES_XML_setName_name                                            0
#define ES_XML_setSettings_settings                                    0
#define ES_XML_text_name                                               0


/**
 *   Class property slots for the "XMLList" class 
 */
#define ES_XMLList__origin                                             5
#define ES_XMLList_XMLList                                             5
#define ES_XMLList_appendChild                                         6
#define ES_XMLList_attribute                                           7
#define ES_XMLList_attributes                                          8
#define ES_XMLList_child                                               9
#define ES_XMLList_childIndex                                          10
#define ES_XMLList_children                                            11
#define ES_XMLList_comments                                            12
#define ES_XMLList_contains                                            13
#define ES_XMLList_copy                                                14
#define ES_XMLList_defaultSettings                                     15
#define ES_XMLList_descendants                                         16
#define ES_XMLList_elements                                            17
#define ES_XMLList_hasComplexContent                                   18
#define ES_XMLList_hasSimpleContent                                    19
#define ES_XMLList_insertChildAfter                                    20
#define ES_XMLList_insertChildBefore                                   21
#define ES_XMLList_localName                                           22
#define ES_XMLList_name                                                23
#define ES_XMLList_nodeKind                                            24
#define ES_XMLList_normalize                                           25
#define ES_XMLList_parent                                              26
#define ES_XMLList_prependChild                                        27
#define ES_XMLList_processingInstructions                              28
#define ES_XMLList_replace                                             29
#define ES_XMLList_setChildren                                         30
#define ES_XMLList_setLocalName                                        31
#define ES_XMLList_setName                                             32
#define ES_XMLList_settings                                            33
#define ES_XMLList_setSettings                                         34
#define ES_XMLList_text                                                35
#define ES_XMLList_toXMLString                                         36
#define ES_XMLList_NUM_CLASS_PROP                                      37

/**
 * Instance slots for "XMLList" type 
 */
#define ES_XMLList_NUM_INSTANCE_PROP                                   0

/**
 * 
 *    Local slots for methods in type XMLList 
 */
#define ES_XMLList_appendChild_child                                   0
#define ES_XMLList_attribute_name                                      0
#define ES_XMLList_child_name                                          0
#define ES_XMLList_contains_obj                                        0
#define ES_XMLList_descendants_name                                    0
#define ES_XMLList_elements_name                                       0
#define ES_XMLList_insertChildAfter_marker                             0
#define ES_XMLList_insertChildAfter_child                              1
#define ES_XMLList_insertChildBefore_marker                            0
#define ES_XMLList_insertChildBefore_child                             1
#define ES_XMLList_prependChild_child                                  0
#define ES_XMLList_processingInstructions_name                         0
#define ES_XMLList_replace_property                                    0
#define ES_XMLList_replace_value                                       1
#define ES_XMLList_setChildren_properties                              0
#define ES_XMLList_setLocalName_name                                   0
#define ES_XMLList_setName_name                                        0
#define ES_XMLList_setSettings_settings                                0
#define ES_XMLList_text_name                                           0

#define _ES_CHECKSUM_ejs 2035482

#endif
