/*
 * ejs.web.slots.h -- Property slot definitions for the "ejs.web" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 0.9.8.
 */

#ifndef _h_SLOTS_EjsWebSlots
#define _h_SLOTS_EjsWebSlots 1


/**
 * Slots for the "ejs.web" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "Controller" class 
 */
#define ES_ejs_web_Controller__origin                                  5
#define ES_ejs_web_Controller_ejs_web_initialize                       5
#define ES_ejs_web_Controller_ejs_web_cache                            6
#define ES_ejs_web_Controller_ejs_web_createSession                    7
#define ES_ejs_web_Controller_ejs_web_destroySession                   8
#define ES_ejs_web_Controller_ejs_web_discardOutput                    9
#define ES_ejs_web_Controller_ejs_web_beforeFilter                     10
#define ES_ejs_web_Controller_ejs_web_afterFilter                      11
#define ES_ejs_web_Controller_ejs_web_wrapFilter                       12
#define ES_ejs_web_Controller_runFilters                               13
#define ES_ejs_web_Controller_ejs_web_doAction                         14
#define ES_ejs_web_Controller_ejs_web_sendError                        15
#define ES_ejs_web_Controller_ejs_web_escapeHtml                       16
#define ES_ejs_web_Controller_ejs_web_html                             17
#define ES_ejs_web_Controller_ejs_web_inform                           18
#define ES_ejs_web_Controller_ejs_web_error                            19
#define ES_ejs_web_Controller_ejs_web_keepAlive                        20
#define ES_ejs_web_Controller_ejs_web_loadView                         21
#define ES_ejs_web_Controller_ejs_web_makeUrl                          22
#define ES_ejs_web_Controller_ejs_web_redirectUrl                      23
#define ES_ejs_web_Controller_ejs_web_redirect                         24
#define ES_ejs_web_Controller_ejs_web_render                           25
#define ES_ejs_web_Controller_ejs_web_renderFile                       26
#define ES_ejs_web_Controller_ejs_web_renderRaw                        27
#define ES_ejs_web_Controller_ejs_web_renderView                       28
#define ES_ejs_web_Controller_reportError                              29
#define ES_ejs_web_Controller_ejs_web_setCookie                        30
#define ES_ejs_web_Controller_ejs_web_setHeader                        31
#define ES_ejs_web_Controller_ejs_web_setHttpCode                      32
#define ES_ejs_web_Controller_ejs_web_statusMessage                    33
#define ES_ejs_web_Controller_ejs_web_setMimeType                      34
#define ES_ejs_web_Controller_ejs_web_unescapeHtml                     35
#define ES_ejs_web_Controller_ejs_web_warn                             36
#define ES_ejs_web_Controller_ejs_web_write                            37
#define ES_ejs_web_Controller_ejs_web_writeHtml                        38
#define ES_ejs_web_Controller_ejs_web_writeRaw                         39
#define ES_ejs_web_Controller_action_missing                           40
#define ES_ejs_web_Controller_NUM_CLASS_PROP                           41

/**
 * Instance slots for "Controller" type 
 */
#define ES_ejs_web_Controller_actionName                               0
#define ES_ejs_web_Controller_originalActionName                       1
#define ES_ejs_web_Controller_application                              2
#define ES_ejs_web_Controller_appUrl                                   3
#define ES_ejs_web_Controller_controllerName                           4
#define ES_ejs_web_Controller_config                                   5
#define ES_ejs_web_Controller_flash                                    6
#define ES_ejs_web_Controller_home                                     7
#define ES_ejs_web_Controller_host                                     8
#define ES_ejs_web_Controller_params                                   9
#define ES_ejs_web_Controller_request                                  10
#define ES_ejs_web_Controller_response                                 11
#define ES_ejs_web_Controller_session                                  12
#define ES_ejs_web_Controller_isApp                                    13
#define ES_ejs_web_Controller_rendered                                 14
#define ES_ejs_web_Controller_redirected                               15
#define ES_ejs_web_Controller_events                                   16
#define ES_ejs_web_Controller__afterFilters                            17
#define ES_ejs_web_Controller__beforeFilters                           18
#define ES_ejs_web_Controller__wrapFilters                             19
#define ES_ejs_web_Controller_NUM_INSTANCE_PROP                        20

/**
 * 
 *    Local slots for methods in type Controller 
 */
#define ES_ejs_web_Controller_ejs_web_initialize_isApp                 0
#define ES_ejs_web_Controller_ejs_web_initialize_appDir                1
#define ES_ejs_web_Controller_ejs_web_initialize_appUrl                2
#define ES_ejs_web_Controller_ejs_web_initialize_session               3
#define ES_ejs_web_Controller_ejs_web_initialize_host                  4
#define ES_ejs_web_Controller_ejs_web_initialize_request               5
#define ES_ejs_web_Controller_ejs_web_initialize_response              6
#define ES_ejs_web_Controller_ejs_web_initialize_name                  7
#define ES_ejs_web_Controller_ejs_web_initialize__hoisted_8_adapter    8
#define ES_ejs_web_Controller_ejs_web_initialize__hoisted_9_dbname     9
#define ES_ejs_web_Controller_ejs_web_cache_enable                     0
#define ES_ejs_web_Controller_ejs_web_createSession_timeout            0
#define ES_ejs_web_Controller_ejs_web_beforeFilter_fn                  0
#define ES_ejs_web_Controller_ejs_web_beforeFilter_options             1
#define ES_ejs_web_Controller_ejs_web_afterFilter_fn                   0
#define ES_ejs_web_Controller_ejs_web_afterFilter_options              1
#define ES_ejs_web_Controller_ejs_web_wrapFilter_fn                    0
#define ES_ejs_web_Controller_ejs_web_wrapFilter_options               1
#define ES_ejs_web_Controller_runFilters_filters                       0
#define ES_ejs_web_Controller_runFilters__hoisted_1_filter             1
#define ES_ejs_web_Controller_runFilters__hoisted_2_fn                 2
#define ES_ejs_web_Controller_runFilters__hoisted_3_options            3
#define ES_ejs_web_Controller_ejs_web_doAction_act                     0
#define ES_ejs_web_Controller_ejs_web_doAction__hoisted_1_e            1
#define ES_ejs_web_Controller_ejs_web_doAction__hoisted_3_item         3
#define ES_ejs_web_Controller_ejs_web_doAction__hoisted_4_old          4
#define ES_ejs_web_Controller_ejs_web_sendError_code                   0
#define ES_ejs_web_Controller_ejs_web_sendError_msg                    1
#define ES_ejs_web_Controller_ejs_web_escapeHtml_s                     0
#define ES_ejs_web_Controller_ejs_web_html_args                        0
#define ES_ejs_web_Controller_ejs_web_html__hoisted_1_s                1
#define ES_ejs_web_Controller_ejs_web_inform_msg                       0
#define ES_ejs_web_Controller_ejs_web_error_msg                        0
#define ES_ejs_web_Controller_ejs_web_keepAlive_on                     0
#define ES_ejs_web_Controller_ejs_web_loadView_path                    0
#define ES_ejs_web_Controller_ejs_web_makeUrl_action                   0
#define ES_ejs_web_Controller_ejs_web_makeUrl_id                       1
#define ES_ejs_web_Controller_ejs_web_makeUrl_options                  2
#define ES_ejs_web_Controller_ejs_web_makeUrl_cname                    3
#define ES_ejs_web_Controller_ejs_web_makeUrl_url                      4
#define ES_ejs_web_Controller_ejs_web_redirectUrl_url                  0
#define ES_ejs_web_Controller_ejs_web_redirectUrl_code                 1
#define ES_ejs_web_Controller_ejs_web_redirect_action                  0
#define ES_ejs_web_Controller_ejs_web_redirect_id                      1
#define ES_ejs_web_Controller_ejs_web_redirect_options                 2
#define ES_ejs_web_Controller_ejs_web_render_args                      0
#define ES_ejs_web_Controller_ejs_web_renderFile_filename              0
#define ES_ejs_web_Controller_ejs_web_renderFile_file                  1
#define ES_ejs_web_Controller_ejs_web_renderFile__hoisted_2_e          2
#define ES_ejs_web_Controller_ejs_web_renderRaw_args                   0
#define ES_ejs_web_Controller_ejs_web_renderView_viewName              0
#define ES_ejs_web_Controller_ejs_web_renderView_gotError              1
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_2_name       2
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_3_viewClass  3
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_5_e          5
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_7_n          7
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_8_e          8
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_9_msg        9
#define ES_ejs_web_Controller_reportError_code                         0
#define ES_ejs_web_Controller_reportError_msg                          1
#define ES_ejs_web_Controller_reportError_e                            2
#define ES_ejs_web_Controller_ejs_web_setCookie_name                   0
#define ES_ejs_web_Controller_ejs_web_setCookie_value                  1
#define ES_ejs_web_Controller_ejs_web_setCookie_lifetime               2
#define ES_ejs_web_Controller_ejs_web_setCookie_path                   3
#define ES_ejs_web_Controller_ejs_web_setCookie_secure                 4
#define ES_ejs_web_Controller_ejs_web_setHeader_key                    0
#define ES_ejs_web_Controller_ejs_web_setHeader_value                  1
#define ES_ejs_web_Controller_ejs_web_setHeader_allowMultiple          2
#define ES_ejs_web_Controller_ejs_web_setHttpCode_code                 0
#define ES_ejs_web_Controller_ejs_web_statusMessage_args               0
#define ES_ejs_web_Controller_ejs_web_setMimeType_format               0
#define ES_ejs_web_Controller_ejs_web_unescapeHtml_s                   0
#define ES_ejs_web_Controller_ejs_web_warn_msg                         0
#define ES_ejs_web_Controller_ejs_web_write_args                       0
#define ES_ejs_web_Controller_ejs_web_writeHtml_args                   0
#define ES_ejs_web_Controller_ejs_web_writeRaw_args                    0


/**
 *   Class property slots for the "_SoloController" class 
 */
#define ES_ejs_web__SoloController__origin                             41
#define ES_ejs_web__SoloController_NUM_CLASS_PROP                      41

/**
 * Instance slots for "_SoloController" type 
 */
#define ES_ejs_web__SoloController_NUM_INSTANCE_PROP                   20


/**
 *   Class property slots for the "Cookie" class 
 */
#define ES_ejs_web_Cookie__origin                                      5
#define ES_ejs_web_Cookie_NUM_CLASS_PROP                               5

/**
 * Instance slots for "Cookie" type 
 */
#define ES_ejs_web_Cookie_name                                         0
#define ES_ejs_web_Cookie_value                                        1
#define ES_ejs_web_Cookie_domain                                       2
#define ES_ejs_web_Cookie_path                                         3
#define ES_ejs_web_Cookie_NUM_INSTANCE_PROP                            4


/**
 *   Class property slots for the "Host" class 
 */
#define ES_ejs_web_Host__origin                                        5
#define ES_ejs_web_Host_NUM_CLASS_PROP                                 5

/**
 * Instance slots for "Host" type 
 */
#define ES_ejs_web_Host_documentRoot                                   0
#define ES_ejs_web_Host_name                                           1
#define ES_ejs_web_Host_protocol                                       2
#define ES_ejs_web_Host_isVirtualHost                                  3
#define ES_ejs_web_Host_isNamedVirtualHost                             4
#define ES_ejs_web_Host_software                                       5
#define ES_ejs_web_Host_logErrors                                      6
#define ES_ejs_web_Host_NUM_INSTANCE_PROP                              7


/**
 *   Class property slots for the "Request" class 
 */
#define ES_ejs_web_Request__origin                                     5
#define ES_ejs_web_Request_NUM_CLASS_PROP                              5

/**
 * Instance slots for "Request" type 
 */
#define ES_ejs_web_Request_accept                                      0
#define ES_ejs_web_Request_acceptCharset                               1
#define ES_ejs_web_Request_acceptEncoding                              2
#define ES_ejs_web_Request_authAcl                                     3
#define ES_ejs_web_Request_authGroup                                   4
#define ES_ejs_web_Request_authType                                    5
#define ES_ejs_web_Request_authUser                                    6
#define ES_ejs_web_Request_connection                                  7
#define ES_ejs_web_Request_contentLength                               8
#define ES_ejs_web_Request_cookies                                     9
#define ES_ejs_web_Request_extension                                   10
#define ES_ejs_web_Request_files                                       11
#define ES_ejs_web_Request_headers                                     12
#define ES_ejs_web_Request_hostName                                    13
#define ES_ejs_web_Request_method                                      14
#define ES_ejs_web_Request_mimeType                                    15
#define ES_ejs_web_Request_pathInfo                                    16
#define ES_ejs_web_Request_pathTranslated                              17
#define ES_ejs_web_Request_pragma                                      18
#define ES_ejs_web_Request_query                                       19
#define ES_ejs_web_Request_originalUri                                 20
#define ES_ejs_web_Request_referrer                                    21
#define ES_ejs_web_Request_remoteAddress                               22
#define ES_ejs_web_Request_remoteHost                                  23
#define ES_ejs_web_Request_sessionID                                   24
#define ES_ejs_web_Request_url                                         25
#define ES_ejs_web_Request_userAgent                                   26
#define ES_ejs_web_Request_NUM_INSTANCE_PROP                           27


/**
 *   Class property slots for the "Response" class 
 */
#define ES_ejs_web_Response__origin                                    5
#define ES_ejs_web_Response_NUM_CLASS_PROP                             5

/**
 * Instance slots for "Response" type 
 */
#define ES_ejs_web_Response_code                                       0
#define ES_ejs_web_Response_filename                                   1
#define ES_ejs_web_Response_headers                                    2
#define ES_ejs_web_Response_mimeType                                   3
#define ES_ejs_web_Response_NUM_INSTANCE_PROP                          4


/**
 *   Class property slots for the "Session" class 
 */
#define ES_ejs_web_Session__origin                                     5
#define ES_ejs_web_Session_NUM_CLASS_PROP                              5

/**
 * Instance slots for "Session" type 
 */
#define ES_ejs_web_Session_NUM_INSTANCE_PROP                           0


/**
 *   Class property slots for the "UploadFile" class 
 */
#define ES_ejs_web_UploadFile__origin                                  5
#define ES_ejs_web_UploadFile_NUM_CLASS_PROP                           5

/**
 * Instance slots for "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_clientFilename                           0
#define ES_ejs_web_UploadFile_contentType                              1
#define ES_ejs_web_UploadFile_filename                                 2
#define ES_ejs_web_UploadFile_name                                     3
#define ES_ejs_web_UploadFile_size                                     4
#define ES_ejs_web_UploadFile_NUM_INSTANCE_PROP                        5


/**
 *   Class property slots for the "View" class 
 */
#define ES_ejs_web_View__origin                                        5
#define ES_ejs_web_View_View                                           5
#define ES_ejs_web_View__initializer__View_initializer                 6
#define ES_ejs_web_View_render                                         7
#define ES_ejs_web_View_ejs_web_aform                                  8
#define ES_ejs_web_View_ejs_web_alink                                  9
#define ES_ejs_web_View_ejs_web_button                                 10
#define ES_ejs_web_View_ejs_web_buttonLink                             11
#define ES_ejs_web_View_ejs_web_chart                                  12
#define ES_ejs_web_View_ejs_web_checkbox                               13
#define ES_ejs_web_View_ejs_web_endform                                14
#define ES_ejs_web_View_ejs_web_form                                   15
#define ES_ejs_web_View_ejs_web_image                                  16
#define ES_ejs_web_View_ejs_web_input                                  17
#define ES_ejs_web_View_ejs_web_label                                  18
#define ES_ejs_web_View_ejs_web_link                                   19
#define ES_ejs_web_View_ejs_web_extlink                                20
#define ES_ejs_web_View_ejs_web_list                                   21
#define ES_ejs_web_View_ejs_web_mail                                   22
#define ES_ejs_web_View_ejs_web_progress                               23
#define ES_ejs_web_View_ejs_web_radio                                  24
#define ES_ejs_web_View_ejs_web_script                                 25
#define ES_ejs_web_View_ejs_web_status                                 26
#define ES_ejs_web_View_ejs_web_stylesheet                             27
#define ES_ejs_web_View_ejs_web_table                                  28
#define ES_ejs_web_View_ejs_web_tabs                                   29
#define ES_ejs_web_View_ejs_web_text                                   30
#define ES_ejs_web_View_ejs_web_textarea                               31
#define ES_ejs_web_View_ejs_web_tree                                   32
#define ES_ejs_web_View_ejs_web_flash                                  33
#define ES_ejs_web_View_formErrors                                     34
#define ES_ejs_web_View_ejs_web_createSession                          35
#define ES_ejs_web_View_ejs_web_destroySession                         36
#define ES_ejs_web_View_ejs_web_html                                   37
#define ES_ejs_web_View_ejs_web_makeUrl                                38
#define ES_ejs_web_View_ejs_web_redirectUrl                            39
#define ES_ejs_web_View_ejs_web_redirect                               40
#define ES_ejs_web_View_ejs_web_setCookie                              41
#define ES_ejs_web_View_ejs_web_setHeader                              42
#define ES_ejs_web_View_ejs_web_setHttpCode                            43
#define ES_ejs_web_View_ejs_web_setMimeType                            44
#define ES_ejs_web_View_ejs_web_write                                  45
#define ES_ejs_web_View_ejs_web_writeHtml                              46
#define ES_ejs_web_View_ejs_web_writeRaw                               47
#define ES_ejs_web_View_ejs_web_d                                      48
#define ES_ejs_web_View_addHelper                                      49
#define ES_ejs_web_View_getConnector                                   50
#define ES_ejs_web_View_setOptions                                     51
#define ES_ejs_web_View_ejs_web_getValue                               52
#define ES_ejs_web_View_ejs_web_date                                   53
#define ES_ejs_web_View_ejs_web_currency                               54
#define ES_ejs_web_View_ejs_web_number                                 55
#define ES_ejs_web_View_htmlOptions                                    56
#define ES_ejs_web_View_ejs_web_getOptions                             57
#define ES_ejs_web_View_sort                                           58
#define ES_ejs_web_View_filter                                         59
#define ES_ejs_web_View_NUM_CLASS_PROP                                 60

/**
 * Instance slots for "View" type 
 */
#define ES_ejs_web_View_ejs_web_controller                             0
#define ES_ejs_web_View_currentModel                                   1
#define ES_ejs_web_View_config                                         2
#define ES_ejs_web_View_NUM_INSTANCE_PROP                              3

/**
 * 
 *    Local slots for methods in type View 
 */
#define ES_ejs_web_View_View_controller                                0
#define ES_ejs_web_View_ejs_web_aform_action                           0
#define ES_ejs_web_View_ejs_web_aform_record                           1
#define ES_ejs_web_View_ejs_web_aform_options                          2
#define ES_ejs_web_View_ejs_web_aform_connector                        3
#define ES_ejs_web_View_ejs_web_alink_text                             0
#define ES_ejs_web_View_ejs_web_alink_action                           1
#define ES_ejs_web_View_ejs_web_alink_options                          2
#define ES_ejs_web_View_ejs_web_alink_connector                        3
#define ES_ejs_web_View_ejs_web_button_value                           0
#define ES_ejs_web_View_ejs_web_button_buttonName                      1
#define ES_ejs_web_View_ejs_web_button_options                         2
#define ES_ejs_web_View_ejs_web_button_connector                       3
#define ES_ejs_web_View_ejs_web_buttonLink_text                        0
#define ES_ejs_web_View_ejs_web_buttonLink_action                      1
#define ES_ejs_web_View_ejs_web_buttonLink_options                     2
#define ES_ejs_web_View_ejs_web_buttonLink_connector                   3
#define ES_ejs_web_View_ejs_web_chart_initialData                      0
#define ES_ejs_web_View_ejs_web_chart_options                          1
#define ES_ejs_web_View_ejs_web_chart_connector                        2
#define ES_ejs_web_View_ejs_web_checkbox_field                         0
#define ES_ejs_web_View_ejs_web_checkbox_choice                        1
#define ES_ejs_web_View_ejs_web_checkbox_options                       2
#define ES_ejs_web_View_ejs_web_checkbox_value                         3
#define ES_ejs_web_View_ejs_web_checkbox_connector                     4
#define ES_ejs_web_View_ejs_web_endform_connector                      0
#define ES_ejs_web_View_ejs_web_form_action                            0
#define ES_ejs_web_View_ejs_web_form_record                            1
#define ES_ejs_web_View_ejs_web_form_options                           2
#define ES_ejs_web_View_ejs_web_form_connector                         3
#define ES_ejs_web_View_ejs_web_image_image                            0
#define ES_ejs_web_View_ejs_web_image_options                          1
#define ES_ejs_web_View_ejs_web_image_connector                        2
#define ES_ejs_web_View_ejs_web_input_field                            0
#define ES_ejs_web_View_ejs_web_input_options                          1
#define ES_ejs_web_View_ejs_web_label_text                             0
#define ES_ejs_web_View_ejs_web_label_options                          1
#define ES_ejs_web_View_ejs_web_label_connector                        2
#define ES_ejs_web_View_ejs_web_link_text                              0
#define ES_ejs_web_View_ejs_web_link_action                            1
#define ES_ejs_web_View_ejs_web_link_options                           2
#define ES_ejs_web_View_ejs_web_link_connector                         3
#define ES_ejs_web_View_ejs_web_extlink_text                           0
#define ES_ejs_web_View_ejs_web_extlink_url                            1
#define ES_ejs_web_View_ejs_web_extlink_options                        2
#define ES_ejs_web_View_ejs_web_extlink_connector                      3
#define ES_ejs_web_View_ejs_web_list_field                             0
#define ES_ejs_web_View_ejs_web_list_choices                           1
#define ES_ejs_web_View_ejs_web_list_options                           2
#define ES_ejs_web_View_ejs_web_list_value                             3
#define ES_ejs_web_View_ejs_web_list_connector                         4
#define ES_ejs_web_View_ejs_web_mail_nameText                          0
#define ES_ejs_web_View_ejs_web_mail_address                           1
#define ES_ejs_web_View_ejs_web_mail_options                           2
#define ES_ejs_web_View_ejs_web_mail_connector                         3
#define ES_ejs_web_View_ejs_web_progress_initialData                   0
#define ES_ejs_web_View_ejs_web_progress_options                       1
#define ES_ejs_web_View_ejs_web_progress_connector                     2
#define ES_ejs_web_View_ejs_web_radio_field                            0
#define ES_ejs_web_View_ejs_web_radio_choices                          1
#define ES_ejs_web_View_ejs_web_radio_options                          2
#define ES_ejs_web_View_ejs_web_radio_value                            3
#define ES_ejs_web_View_ejs_web_radio_connector                        4
#define ES_ejs_web_View_ejs_web_script_url                             0
#define ES_ejs_web_View_ejs_web_script_options                         1
#define ES_ejs_web_View_ejs_web_script_connector                       2
#define ES_ejs_web_View_ejs_web_script__hoisted_3_u                    3
#define ES_ejs_web_View_ejs_web_status_initialData                     0
#define ES_ejs_web_View_ejs_web_status_options                         1
#define ES_ejs_web_View_ejs_web_status_connector                       2
#define ES_ejs_web_View_ejs_web_stylesheet_url                         0
#define ES_ejs_web_View_ejs_web_stylesheet_options                     1
#define ES_ejs_web_View_ejs_web_stylesheet_connector                   2
#define ES_ejs_web_View_ejs_web_stylesheet__hoisted_3_u                3
#define ES_ejs_web_View_ejs_web_table_data                             0
#define ES_ejs_web_View_ejs_web_table_options                          1
#define ES_ejs_web_View_ejs_web_table_connector                        2
#define ES_ejs_web_View_ejs_web_tabs_initialData                       0
#define ES_ejs_web_View_ejs_web_tabs_options                           1
#define ES_ejs_web_View_ejs_web_tabs_connector                         2
#define ES_ejs_web_View_ejs_web_text_field                             0
#define ES_ejs_web_View_ejs_web_text_options                           1
#define ES_ejs_web_View_ejs_web_text_value                             2
#define ES_ejs_web_View_ejs_web_text_connector                         3
#define ES_ejs_web_View_ejs_web_textarea_field                         0
#define ES_ejs_web_View_ejs_web_textarea_options                       1
#define ES_ejs_web_View_ejs_web_textarea_value                         2
#define ES_ejs_web_View_ejs_web_textarea_connector                     3
#define ES_ejs_web_View_ejs_web_tree_initialData                       0
#define ES_ejs_web_View_ejs_web_tree_options                           1
#define ES_ejs_web_View_ejs_web_tree_connector                         2
#define ES_ejs_web_View_ejs_web_flash_kinds                            0
#define ES_ejs_web_View_ejs_web_flash_options                          1
#define ES_ejs_web_View_ejs_web_flash_cflash                           2
#define ES_ejs_web_View_ejs_web_flash_msgs                             3
#define ES_ejs_web_View_ejs_web_flash__hoisted_4_kind                  4
#define ES_ejs_web_View_ejs_web_flash__hoisted_6_kind                  6
#define ES_ejs_web_View_ejs_web_flash__hoisted_7_msg                   7
#define ES_ejs_web_View_ejs_web_flash__hoisted_8_connector             8
#define ES_ejs_web_View_formErrors_model                               0
#define ES_ejs_web_View_formErrors_errors                              1
#define ES_ejs_web_View_formErrors__hoisted_2_e                        2
#define ES_ejs_web_View_ejs_web_createSession_timeout                  0
#define ES_ejs_web_View_ejs_web_html_args                              0
#define ES_ejs_web_View_ejs_web_makeUrl_action                         0
#define ES_ejs_web_View_ejs_web_makeUrl_id                             1
#define ES_ejs_web_View_ejs_web_makeUrl_options                        2
#define ES_ejs_web_View_ejs_web_redirectUrl_url                        0
#define ES_ejs_web_View_ejs_web_redirectUrl_code                       1
#define ES_ejs_web_View_ejs_web_redirect_action                        0
#define ES_ejs_web_View_ejs_web_redirect_id                            1
#define ES_ejs_web_View_ejs_web_redirect_options                       2
#define ES_ejs_web_View_ejs_web_setCookie_name                         0
#define ES_ejs_web_View_ejs_web_setCookie_value                        1
#define ES_ejs_web_View_ejs_web_setCookie_lifetime                     2
#define ES_ejs_web_View_ejs_web_setCookie_path                         3
#define ES_ejs_web_View_ejs_web_setCookie_secure                       4
#define ES_ejs_web_View_ejs_web_setHeader_key                          0
#define ES_ejs_web_View_ejs_web_setHeader_value                        1
#define ES_ejs_web_View_ejs_web_setHeader_allowMultiple                2
#define ES_ejs_web_View_ejs_web_setHttpCode_code                       0
#define ES_ejs_web_View_ejs_web_setMimeType_format                     0
#define ES_ejs_web_View_ejs_web_write_args                             0
#define ES_ejs_web_View_ejs_web_writeHtml_args                         0
#define ES_ejs_web_View_ejs_web_writeRaw_args                          0
#define ES_ejs_web_View_ejs_web_d_args                                 0
#define ES_ejs_web_View_ejs_web_d_e                                    1
#define ES_ejs_web_View_addHelper_fun                                  0
#define ES_ejs_web_View_addHelper_overwrite                            1
#define ES_ejs_web_View_addHelper_name                                 2
#define ES_ejs_web_View_getConnector_kind                              0
#define ES_ejs_web_View_getConnector_options                           1
#define ES_ejs_web_View_getConnector_connectorName                     2
#define ES_ejs_web_View_getConnector_name                              3
#define ES_ejs_web_View_getConnector__hoisted_4_e                      4
#define ES_ejs_web_View_setOptions_field                               0
#define ES_ejs_web_View_setOptions_options                             1
#define ES_ejs_web_View_ejs_web_getValue_model                         0
#define ES_ejs_web_View_ejs_web_getValue_field                         1
#define ES_ejs_web_View_ejs_web_getValue_options                       2
#define ES_ejs_web_View_ejs_web_getValue_value                         3
#define ES_ejs_web_View_ejs_web_getValue_typeName                      4
#define ES_ejs_web_View_ejs_web_getValue_fmt                           5
#define ES_ejs_web_View_ejs_web_date_fmt                               0
#define ES_ejs_web_View_ejs_web_date___fun_4958__                      1
#define ES_ejs_web_View_ejs_web_currency_fmt                           0
#define ES_ejs_web_View_ejs_web_currency___fun_4992__                  1
#define ES_ejs_web_View_ejs_web_number_fmt                             0
#define ES_ejs_web_View_ejs_web_number___fun_5022__                    1
#define ES_ejs_web_View_ejs_web_getOptions_options                     0
#define ES_ejs_web_View_ejs_web_getOptions_result                      1
#define ES_ejs_web_View_ejs_web_getOptions__hoisted_2_option           2
#define ES_ejs_web_View_ejs_web_getOptions__hoisted_3_mapped           3
#define ES_ejs_web_View_sort_data                                      0
#define ES_ejs_web_View_sort_tmp                                       1
#define ES_ejs_web_View_filter_data                                    0
#define ES_ejs_web_View_filter__hoisted_1_i                            1
#define ES_ejs_web_View_filter__hoisted_2_found                        2
#define ES_ejs_web_View_filter__hoisted_3_f                            3


/**
 *   Class property slots for the "Model" class 
 */
#define ES_Model__origin                                               5
#define ES_Model__initializer__Record_initializer                      5
#define ES_Model__belongsTo                                            6
#define ES_Model__className                                            7
#define ES_Model__columnNames                                          8
#define ES_Model__columnTypes                                          9
#define ES_Model__sqlColumnTypes                                       10
#define ES_Model__db                                                   11
#define ES_Model__foreignId                                            12
#define ES_Model__keyName                                              13
#define ES_Model__tableName                                            14
#define ES_Model__traceSql                                             15
#define ES_Model__validations                                          16
#define ES_Model__beforeFilters                                        17
#define ES_Model__afterFilters                                         18
#define ES_Model__wrapFilters                                          19
#define ES_Model_constructor                                           20
#define ES_Model_beforeFilter                                          21
#define ES_Model_afterFilter                                           22
#define ES_Model_wrapFilter                                            23
#define ES_Model_runFilters                                            24
#define ES_Model_save                                                  25
#define ES_Model_saveUpdate                                            26
#define ES_Model_belongsTo                                             27
#define ES_Model_createRecord                                          28
#define ES_Model_find                                                  29
#define ES_Model_findAll                                               30
#define ES_Model_findOneWhere                                          31
#define ES_Model_findWhere                                             32
#define ES_Model_includeJoin                                           33
#define ES_Model_innerFind                                             34
#define ES_Model_getDb                                                 35
#define ES_Model_columnNames                                           36
#define ES_Model_columnTitles                                          37
#define ES_Model_getKeyName                                            38
#define ES_Model_getNumRows                                            39
#define ES_Model_getSchema                                             40
#define ES_Model_getTableName                                          41
#define ES_Model_hasMany                                               42
#define ES_Model_hasAndBelongsToMany                                   43
#define ES_Model_hasOne                                                44
#define ES_Model_loadReference                                         45
#define ES_Model_log                                                   46
#define ES_Model_logResult                                             47
#define ES_Model_mapSqlTypeToEjs                                       48
#define ES_Model_remove                                                49
#define ES_Model_setDb                                                 50
#define ES_Model_setup                                                 51
#define ES_Model_setTableName                                          52
#define ES_Model_setKeyName                                            53
#define ES_Model_sql                                                   54
#define ES_Model_trace                                                 55
#define ES_Model_validateFormat                                        56
#define ES_Model_validateNumber                                        57
#define ES_Model_validatePresence                                      58
#define ES_Model_validateUnique                                        59
#define ES_Model_ErrorMessages                                         60
#define ES_Model_checkFormat                                           61
#define ES_Model_checkNumber                                           62
#define ES_Model_checkPresent                                          63
#define ES_Model_checkUnique                                           64
#define ES_Model_error                                                 65
#define ES_Model_validateModel                                         66
#define ES_Model_getErrors                                             67
#define ES_Model_hasError                                              68
#define ES_Model_getFieldType                                          69
#define ES_Model_coerceTypes                                           70
#define ES_Model_Model                                                 71
#define ES_Model__initializer__Model_initializer                       72
#define ES_Model_NUM_CLASS_PROP                                        73

/**
 * Instance slots for "Model" type 
 */
#define ES_Model__keyValue                                             0
#define ES_Model__errors                                               1
#define ES_Model_NUM_INSTANCE_PROP                                     2

/**
 * 
 *    Local slots for methods in type Model 
 */
#define ES_Model_constructor_fields                                    0
#define ES_Model_constructor__hoisted_1_field                          1
#define ES_Model_beforeFilter_fn                                       0
#define ES_Model_beforeFilter_options                                  1
#define ES_Model_afterFilter_fn                                        0
#define ES_Model_afterFilter_options                                   1
#define ES_Model_wrapFilter_fn                                         0
#define ES_Model_wrapFilter_options                                    1
#define ES_Model_runFilters_filters                                    0
#define ES_Model_runFilters__hoisted_1_filter                          1
#define ES_Model_runFilters__hoisted_2_fn                              2
#define ES_Model_runFilters__hoisted_3_options                         3
#define ES_Model_save_sql                                              0
#define ES_Model_save_result                                           1
#define ES_Model_save__hoisted_2_field                                 2
#define ES_Model_save__hoisted_3_field                                 3
#define ES_Model_save__hoisted_5_field                                 5
#define ES_Model_saveUpdate_fields                                     0
#define ES_Model_saveUpdate__hoisted_1_field                           1
#define ES_Model_belongsTo_owner                                       0
#define ES_Model_belongsTo_options                                     1
#define ES_Model_createRecord_rowData                                  0
#define ES_Model_createRecord_rec                                      1
#define ES_Model_createRecord__hoisted_2_field                         2
#define ES_Model_find_key                                              0
#define ES_Model_find_options                                          1
#define ES_Model_find_grid                                             2
#define ES_Model_findAll_options                                       0
#define ES_Model_findAll_grid                                          1
#define ES_Model_findAll__hoisted_2_i                                  2
#define ES_Model_findOneWhere_where                                    0
#define ES_Model_findOneWhere_grid                                     1
#define ES_Model_findWhere_where                                       0
#define ES_Model_findWhere_count                                       1
#define ES_Model_findWhere_grid                                        2
#define ES_Model_findWhere__hoisted_3_i                                3
#define ES_Model_includeJoin_joins                                     0
#define ES_Model_includeJoin_cmd                                       1
#define ES_Model_includeJoin__hoisted_2_join                           2
#define ES_Model_innerFind_key                                         0
#define ES_Model_innerFind_options                                     1
#define ES_Model_innerFind_cmd                                         2
#define ES_Model_innerFind_columns                                     3
#define ES_Model_innerFind_from                                        4
#define ES_Model_innerFind_conditions                                  5
#define ES_Model_innerFind_where                                       6
#define ES_Model_innerFind_db                                          7
#define ES_Model_innerFind_results                                     8
#define ES_Model_innerFind__hoisted_9_index                            9
#define ES_Model_innerFind__hoisted_11_owner                           11
#define ES_Model_innerFind__hoisted_12_owner                           12
#define ES_Model_innerFind__hoisted_13_tname                           13
#define ES_Model_innerFind__hoisted_14_parts                           14
#define ES_Model_innerFind__hoisted_16_cond                            16
#define ES_Model_innerFind__hoisted_17_field                           17
#define ES_Model_innerFind__hoisted_19_e                               19
#define ES_Model_columnNames_result                                    0
#define ES_Model_columnNames__hoisted_1_name                           1
#define ES_Model_columnTitles_result                                   0
#define ES_Model_columnTitles__hoisted_1_title                         1
#define ES_Model_getNumRows_cmd                                        0
#define ES_Model_getNumRows_grid                                       1
#define ES_Model_getSchema_sql                                         0
#define ES_Model_getSchema_grid                                        1
#define ES_Model_getSchema__hoisted_2_row                              2
#define ES_Model_getSchema__hoisted_3_name                             3
#define ES_Model_hasMany_model                                         0
#define ES_Model_hasMany_options                                       1
#define ES_Model_hasAndBelongsToMany_thing                             0
#define ES_Model_hasAndBelongsToMany_options                           1
#define ES_Model_hasOne_model                                          0
#define ES_Model_hasOne_options                                        1
#define ES_Model_loadReference_model                                   0
#define ES_Model_loadReference_key                                     1
#define ES_Model_loadReference_hasMany                                 2
#define ES_Model_loadReference_data                                    3
#define ES_Model_loadReference__hoisted_4_result                       4
#define ES_Model_loadReference__hoisted_5_item                         5
#define ES_Model_log_where                                             0
#define ES_Model_log_cmd                                               1
#define ES_Model_logResult_data                                        0
#define ES_Model_mapSqlTypeToEjs_sqlType                               0
#define ES_Model_mapSqlTypeToEjs_ejsType                               1
#define ES_Model_remove_keys                                           0
#define ES_Model_remove__hoisted_1_key                                 1
#define ES_Model_remove__hoisted_2_cmd                                 2
#define ES_Model_setDb_dbase                                           0
#define ES_Model_setup_database                                        0
#define ES_Model_setTableName_name                                     0
#define ES_Model_setKeyName_value                                      0
#define ES_Model_sql_cmd                                               0
#define ES_Model_sql_count                                             1
#define ES_Model_trace_on                                              0
#define ES_Model_validateFormat_fields                                 0
#define ES_Model_validateFormat_options                                1
#define ES_Model_validateNumber_fields                                 0
#define ES_Model_validateNumber_options                                1
#define ES_Model_validatePresence_fields                               0
#define ES_Model_validatePresence_options                              1
#define ES_Model_validateUnique_fields                                 0
#define ES_Model_validateUnique_options                                1
#define ES_Model_checkFormat_thisObj                                   0
#define ES_Model_checkFormat_field                                     1
#define ES_Model_checkFormat_value                                     2
#define ES_Model_checkFormat_options                                   3
#define ES_Model_checkNumber_thisObj                                   0
#define ES_Model_checkNumber_field                                     1
#define ES_Model_checkNumber_value                                     2
#define ES_Model_checkNumber_options                                   3
#define ES_Model_checkPresent_thisObj                                  0
#define ES_Model_checkPresent_field                                    1
#define ES_Model_checkPresent_value                                    2
#define ES_Model_checkPresent_options                                  3
#define ES_Model_checkUnique_thisObj                                   0
#define ES_Model_checkUnique_field                                     1
#define ES_Model_checkUnique_value                                     2
#define ES_Model_checkUnique_options                                   3
#define ES_Model_error_field                                           0
#define ES_Model_error_msg                                             1
#define ES_Model_validateModel__hoisted_0_validation                   0
#define ES_Model_validateModel__hoisted_1_field                        1
#define ES_Model_hasError_field                                        0
#define ES_Model_getFieldType_field                                    0
#define ES_Model_coerceTypes__hoisted_0_field                          0
#define ES_Model_coerceTypes__hoisted_1_value                          1
#define ES_Model_Model_fields                                          0


/**
 *   Class property slots for the "HtmlConnector" class 
 */
#define ES_ejs_web_HtmlConnector__origin                               5
#define ES_ejs_web_HtmlConnector_ejs_web_aform                         5
#define ES_ejs_web_HtmlConnector_ejs_web_alink                         6
#define ES_ejs_web_HtmlConnector_ejs_web_button                        7
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink                    8
#define ES_ejs_web_HtmlConnector_ejs_web_chart                         9
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox                      10
#define ES_ejs_web_HtmlConnector_ejs_web_endform                       11
#define ES_ejs_web_HtmlConnector_ejs_web_flash                         12
#define ES_ejs_web_HtmlConnector_ejs_web_form                          13
#define ES_ejs_web_HtmlConnector_ejs_web_image                         14
#define ES_ejs_web_HtmlConnector_ejs_web_label                         15
#define ES_ejs_web_HtmlConnector_ejs_web_link                          16
#define ES_ejs_web_HtmlConnector_ejs_web_extlink                       17
#define ES_ejs_web_HtmlConnector_ejs_web_list                          18
#define ES_ejs_web_HtmlConnector_ejs_web_mail                          19
#define ES_ejs_web_HtmlConnector_ejs_web_progress                      20
#define ES_ejs_web_HtmlConnector_ejs_web_radio                         21
#define ES_ejs_web_HtmlConnector_ejs_web_script                        22
#define ES_ejs_web_HtmlConnector_ejs_web_status                        23
#define ES_ejs_web_HtmlConnector_ejs_web_stylesheet                    24
#define ES_ejs_web_HtmlConnector_ejs_web_tabs                          25
#define ES_ejs_web_HtmlConnector_ejs_web_table                         26
#define ES_ejs_web_HtmlConnector_ejs_web_text                          27
#define ES_ejs_web_HtmlConnector_ejs_web_textarea                      28
#define ES_ejs_web_HtmlConnector_ejs_web_tree                          29
#define ES_ejs_web_HtmlConnector_getTextKind                           30
#define ES_ejs_web_HtmlConnector_getOptions                            31
#define ES_ejs_web_HtmlConnector_write                                 32
#define ES_ejs_web_HtmlConnector_NUM_CLASS_PROP                        33

/**
 * Instance slots for "HtmlConnector" type 
 */
#define ES_ejs_web_HtmlConnector_NUM_INSTANCE_PROP                     0

/**
 * 
 *    Local slots for methods in type HtmlConnector 
 */
#define ES_ejs_web_HtmlConnector_ejs_web_aform_record                  0
#define ES_ejs_web_HtmlConnector_ejs_web_aform_url                     1
#define ES_ejs_web_HtmlConnector_ejs_web_aform_options                 2
#define ES_ejs_web_HtmlConnector_ejs_web_alink_text                    0
#define ES_ejs_web_HtmlConnector_ejs_web_alink_url                     1
#define ES_ejs_web_HtmlConnector_ejs_web_alink_options                 2
#define ES_ejs_web_HtmlConnector_ejs_web_button_value                  0
#define ES_ejs_web_HtmlConnector_ejs_web_button_buttonName             1
#define ES_ejs_web_HtmlConnector_ejs_web_button_options                2
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink_text               0
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink_url                1
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink_options            2
#define ES_ejs_web_HtmlConnector_ejs_web_chart_data                    0
#define ES_ejs_web_HtmlConnector_ejs_web_chart_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_name                 0
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_value                1
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_submitValue          2
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_options              3
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_checked              4
#define ES_ejs_web_HtmlConnector_ejs_web_flash_kind                    0
#define ES_ejs_web_HtmlConnector_ejs_web_flash_msg                     1
#define ES_ejs_web_HtmlConnector_ejs_web_flash_options                 2
#define ES_ejs_web_HtmlConnector_ejs_web_form_record                   0
#define ES_ejs_web_HtmlConnector_ejs_web_form_url                      1
#define ES_ejs_web_HtmlConnector_ejs_web_form_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_image_src                     0
#define ES_ejs_web_HtmlConnector_ejs_web_image_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_label_text                    0
#define ES_ejs_web_HtmlConnector_ejs_web_label_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_link_text                     0
#define ES_ejs_web_HtmlConnector_ejs_web_link_url                      1
#define ES_ejs_web_HtmlConnector_ejs_web_link_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_extlink_text                  0
#define ES_ejs_web_HtmlConnector_ejs_web_extlink_url                   1
#define ES_ejs_web_HtmlConnector_ejs_web_extlink_options               2
#define ES_ejs_web_HtmlConnector_ejs_web_list_name                     0
#define ES_ejs_web_HtmlConnector_ejs_web_list_choices                  1
#define ES_ejs_web_HtmlConnector_ejs_web_list_defaultValue             2
#define ES_ejs_web_HtmlConnector_ejs_web_list_options                  3
#define ES_ejs_web_HtmlConnector_ejs_web_list_isSelected               4
#define ES_ejs_web_HtmlConnector_ejs_web_list_i                        5
#define ES_ejs_web_HtmlConnector_ejs_web_list__hoisted_6_choice        6
#define ES_ejs_web_HtmlConnector_ejs_web_list__hoisted_7_field         7
#define ES_ejs_web_HtmlConnector_ejs_web_mail_name                     0
#define ES_ejs_web_HtmlConnector_ejs_web_mail_address                  1
#define ES_ejs_web_HtmlConnector_ejs_web_mail_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_progress_data                 0
#define ES_ejs_web_HtmlConnector_ejs_web_progress_options              1
#define ES_ejs_web_HtmlConnector_ejs_web_radio_name                    0
#define ES_ejs_web_HtmlConnector_ejs_web_radio_selected                1
#define ES_ejs_web_HtmlConnector_ejs_web_radio_choices                 2
#define ES_ejs_web_HtmlConnector_ejs_web_radio_options                 3
#define ES_ejs_web_HtmlConnector_ejs_web_radio_checked                 4
#define ES_ejs_web_HtmlConnector_ejs_web_radio__hoisted_5_v            5
#define ES_ejs_web_HtmlConnector_ejs_web_radio__hoisted_7_item         7
#define ES_ejs_web_HtmlConnector_ejs_web_script_url                    0
#define ES_ejs_web_HtmlConnector_ejs_web_script_options                1
#define ES_ejs_web_HtmlConnector_ejs_web_status_data                   0
#define ES_ejs_web_HtmlConnector_ejs_web_status_options                1
#define ES_ejs_web_HtmlConnector_ejs_web_stylesheet_url                0
#define ES_ejs_web_HtmlConnector_ejs_web_stylesheet_options            1
#define ES_ejs_web_HtmlConnector_ejs_web_tabs_tabs                     0
#define ES_ejs_web_HtmlConnector_ejs_web_tabs_options                  1
#define ES_ejs_web_HtmlConnector_ejs_web_tabs__hoisted_2_t             2
#define ES_ejs_web_HtmlConnector_ejs_web_tabs__hoisted_3_name          3
#define ES_ejs_web_HtmlConnector_ejs_web_tabs__hoisted_4_url           4
#define ES_ejs_web_HtmlConnector_ejs_web_table_data                    0
#define ES_ejs_web_HtmlConnector_ejs_web_table_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_table_line                    2
#define ES_ejs_web_HtmlConnector_ejs_web_table_columns                 3
#define ES_ejs_web_HtmlConnector_ejs_web_table_row                     4
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_5_name         5
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_6_column       6
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_7_name         7
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_8_header       8
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_9_width        9
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_11_name        11
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_13_r           13
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_14_url         14
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_15_style       15
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_16_name        16
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_17_column      17
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_18_cellStyle   18
#define ES_ejs_web_HtmlConnector_ejs_web_text_name                     0
#define ES_ejs_web_HtmlConnector_ejs_web_text_value                    1
#define ES_ejs_web_HtmlConnector_ejs_web_text_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_textarea_name                 0
#define ES_ejs_web_HtmlConnector_ejs_web_textarea_value                1
#define ES_ejs_web_HtmlConnector_ejs_web_textarea_options              2
#define ES_ejs_web_HtmlConnector_ejs_web_tree_data                     0
#define ES_ejs_web_HtmlConnector_ejs_web_tree_options                  1
#define ES_ejs_web_HtmlConnector_getTextKind_options                   0
#define ES_ejs_web_HtmlConnector_getTextKind_kind                      1
#define ES_ejs_web_HtmlConnector_getOptions_options                    0
#define ES_ejs_web_HtmlConnector_write_str                             0


/**
 *   Class property slots for the "GoogleConnector" class 
 */
#define ES_ejs_web_GoogleConnector__origin                             5
#define ES_ejs_web_GoogleConnector_GoogleConnector                     5
#define ES_ejs_web_GoogleConnector_scriptHeader                        6
#define ES_ejs_web_GoogleConnector_ejs_web_table                       7
#define ES_ejs_web_GoogleConnector_ejs_web_chart                       8
#define ES_ejs_web_GoogleConnector_getOptions                          9
#define ES_ejs_web_GoogleConnector_write                               10
#define ES_ejs_web_GoogleConnector_NUM_CLASS_PROP                      11

/**
 * Instance slots for "GoogleConnector" type 
 */
#define ES_ejs_web_GoogleConnector_nextId                              0
#define ES_ejs_web_GoogleConnector_NUM_INSTANCE_PROP                   1

/**
 * 
 *    Local slots for methods in type GoogleConnector 
 */
#define ES_ejs_web_GoogleConnector_scriptHeader_kind                   0
#define ES_ejs_web_GoogleConnector_scriptHeader_id                     1
#define ES_ejs_web_GoogleConnector_ejs_web_table_grid                  0
#define ES_ejs_web_GoogleConnector_ejs_web_table_options               1
#define ES_ejs_web_GoogleConnector_ejs_web_table_id                    2
#define ES_ejs_web_GoogleConnector_ejs_web_table_columns               3
#define ES_ejs_web_GoogleConnector_ejs_web_table_firstLine             4
#define ES_ejs_web_GoogleConnector_ejs_web_table_goptions              5
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_6_i          6
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_8_name       8
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_10_name      10
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_12_row       12
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_13_col       13
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_14_name      14
#define ES_ejs_web_GoogleConnector_ejs_web_chart_grid                  0
#define ES_ejs_web_GoogleConnector_ejs_web_chart_options               1
#define ES_ejs_web_GoogleConnector_ejs_web_chart_id                    2
#define ES_ejs_web_GoogleConnector_ejs_web_chart_columns               3
#define ES_ejs_web_GoogleConnector_ejs_web_chart_firstLine             4
#define ES_ejs_web_GoogleConnector_ejs_web_chart_col                   5
#define ES_ejs_web_GoogleConnector_ejs_web_chart_dataType              6
#define ES_ejs_web_GoogleConnector_ejs_web_chart_goptions              7
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_8_name       8
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_10_row       10
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_11_col2      11
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_12_name2     12
#define ES_ejs_web_GoogleConnector_getOptions_options                  0
#define ES_ejs_web_GoogleConnector_getOptions_defaults                 1
#define ES_ejs_web_GoogleConnector_getOptions_result                   2
#define ES_ejs_web_GoogleConnector_getOptions__hoisted_3_word          3
#define ES_ejs_web_GoogleConnector_write_str                           0

#define _ES_CHECKSUM_ejs_web 3386405

#endif
