#
#	Makefile for src/include
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

include 		.makedep

dependExtra:
	@for f in master/* ; do \
		f=`basename $$f` ; \
		cp master/$$f . ; \
	done

cleanExtra:
	@for f in master/* ; do \
		f=`basename $$f` ; \
		cp master/$$f . ; \
	done
